# Generated by Django 3.2.15 on 2022-11-04 22:43

import apps.general.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(blank=True, max_length=500, null=True)),
                ('symbol', models.CharField(blank=True, max_length=5, null=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('spanish_name', models.CharField(blank=True, max_length=500, null=True)),
                ('accronym', models.CharField(blank=True, max_length=10, null=True)),
                ('iso', models.CharField(blank=True, max_length=500, null=True)),
                ('decimals', models.IntegerField(blank=True, default=2)),
                ('countries', models.ManyToManyField(blank=True, related_name='currency', to='countries.Country')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'db_table': 'assets_currencies',
            },
            bases=(models.Model, apps.general.mixins.BaseToAllMixin),
        ),
    ]
