# Generated by Django 4.2.7 on 2023-11-26 16:44

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import src.general.mixins


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("currencies", "0002_userdefaultcurrency"),
    ]

    operations = [
        migrations.RenameField(
            model_name="currency",
            old_name="accronym",
            new_name="code",
        ),
        migrations.AlterField(
            model_name="currency",
            name="code",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="currency",
            name="currency",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="currency",
            name="iso",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="currency",
            name="name",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="currency",
            name="spanish_name",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="currency",
            name="symbol",
            field=models.CharField(blank=True, default="", max_length=5),
        ),
        migrations.AlterField(
            model_name="userdefaultcurrency",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="currency",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conversion_rate",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=100
                    ),
                ),
                ("date", models.DateField()),
                (
                    "base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates_base",
                        to="currencies.currency",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates_target",
                        to="currencies.currency",
                    ),
                ),
            ],
            options={
                "db_table": "assets_exchange_rate",
                "ordering": ["created_at"],
                "unique_together": {("base", "target", "date")},
            },
            bases=(models.Model, src.general.mixins.BaseToAllMixin),
        ),
    ]
