# Generated by Django 4.2.7 on 2023-12-23 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("currencies", "0003_remove_currency_accronym_currency_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchangerate",
            name="base",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rates_from",
                to="currencies.currency",
            ),
        ),
        migrations.AlterField(
            model_name="exchangerate",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rates_to",
                to="currencies.currency",
            ),
        ),
    ]
