CONTENT_FOR_PROMOTION = "promotion"
CONTENT_FOR_SUGGESTION = "suggestion"
CONTENT_FOR_ANNOUNCEMENT = "announcement"
CONTENT_FOR_WELCOME = "welcome"
CONTENT_FOR_ENGAGEMENT = "engagement"

CONTENT_PURPOSES = (
    (CONTENT_FOR_PROMOTION, "Promotion"),
    (CONTENT_FOR_SUGGESTION, "Suggestion"),
    (CONTENT_FOR_ANNOUNCEMENT, "Announcement"),
    (CONTENT_FOR_WELCOME, "Welcome"),
    (CONTENT_FOR_ENGAGEMENT, "Engagement"),
)