CONTENT_FOR_PROMOTION = "promotion"
CONTENT_FOR_SUGGESTION = "suggestion"
CONTENT_FOR_ANNOUNCEMENT = "announcement"
CONTENT_FOR_WELCOME = "welcome"
CONTENT_FOR_ENGAGEMENT = "engagement"
CONTENT_FOR_ENGAGEMENT_USER_FIRST_CALL = f"{CONTENT_FOR_ENGAGEMENT}-user-first-call"
CONTENT_FOR_ENGAGEMENT_USER_NO_ACTIVE = f"{CONTENT_FOR_ENGAGEMENT}-user-no-active"
CONTENT_FOR_ENGAGEMENT_USER_LITTLE_ACTIVE = f"{CONTENT_FOR_ENGAGEMENT}-user-little-active"
CONTENT_FOR_NEWSLETTER = "newsletter"
CONTENT_FOR_NEWSLETTER_BLOG = f"{CONTENT_FOR_NEWSLETTER}-blog"
CONTENT_FOR_NEWSLETTER_PUBLIC_BLOG = f"{CONTENT_FOR_NEWSLETTER}-public-blog"
CONTENT_FOR_NEWSLETTER_TERM = f"{CONTENT_FOR_NEWSLETTER}-term"
CONTENT_FOR_NEWSLETTER_COMPANY = f"{CONTENT_FOR_NEWSLETTER}-company"
CONTENT_FOR_NEWSLETTER_COMPANY_NEWS = f"{CONTENT_FOR_NEWSLETTER_COMPANY}-news"
CONTENT_FOR_NEWSLETTER_COMPANY_REPORT = f"{CONTENT_FOR_NEWSLETTER_COMPANY}-report"

LIST_CONTENT_ENGAGEMENT = (
    CONTENT_FOR_ENGAGEMENT,
    CONTENT_FOR_ENGAGEMENT_USER_FIRST_CALL,
    CONTENT_FOR_ENGAGEMENT_USER_NO_ACTIVE,
    CONTENT_FOR_ENGAGEMENT_USER_LITTLE_ACTIVE,
)

LIST_CONTENT_NEWSLETTER = (
    CONTENT_FOR_NEWSLETTER,
    CONTENT_FOR_NEWSLETTER_BLOG,
    CONTENT_FOR_NEWSLETTER_PUBLIC_BLOG,
    CONTENT_FOR_NEWSLETTER_TERM,
    CONTENT_FOR_NEWSLETTER_COMPANY,
    CONTENT_FOR_NEWSLETTER_COMPANY_NEWS,
    CONTENT_FOR_NEWSLETTER_COMPANY_REPORT,
)

CONTENT_PURPOSES = (
    (CONTENT_FOR_PROMOTION, "Promotion"),
    (CONTENT_FOR_SUGGESTION, "Suggestion"),
    (CONTENT_FOR_ANNOUNCEMENT, "Announcement"),
    (CONTENT_FOR_WELCOME, "Welcome"),
    (CONTENT_FOR_ENGAGEMENT, "Engagement"),
    (CONTENT_FOR_ENGAGEMENT_USER_NO_ACTIVE, "Engagement user no active"),
    (CONTENT_FOR_ENGAGEMENT_USER_LITTLE_ACTIVE, "Engagement user little active"),
    (CONTENT_FOR_ENGAGEMENT_USER_FIRST_CALL, "Engagement user first call"),
    (CONTENT_FOR_NEWSLETTER, "Newsletter"),
    (CONTENT_FOR_NEWSLETTER_BLOG, "Newsletter for blog"),
    (CONTENT_FOR_NEWSLETTER_PUBLIC_BLOG, "Newsletter  for public blog"),
    (CONTENT_FOR_NEWSLETTER_TERM, "Newsletter for term"),
    (CONTENT_FOR_NEWSLETTER_COMPANY, "Newsletter for company"),
    (CONTENT_FOR_NEWSLETTER_COMPANY_NEWS, "Newsletter for company news"),
    (CONTENT_FOR_NEWSLETTER_COMPANY_REPORT, "Newsletter for company report"),
)

CONTENT_PURPOSES_MAP = {key: value for key, value in CONTENT_PURPOSES}

WHOM_TO_SEND_EMAIL_ALL = "all"
WHOM_TO_SEND_EMAIL_TYPE_RELATED = "type_related"
WHOM_TO_SEND_EMAIL_SELECTED = "selected"

WHOM_TO_SEND_EMAIL = (
    (WHOM_TO_SEND_EMAIL_ALL, "All"),
    (WHOM_TO_SEND_EMAIL_TYPE_RELATED, "Type related"),
    (WHOM_TO_SEND_EMAIL_SELECTED, "Selected"),
)

COMMENT_PURCHASED_PRODUCT = "Comenta tu úlitma compra"
