# Generated by Django 3.2.16 on 2023-10-01 16:46

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import src.general.mixins


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('currencies', '0002_userdefaultcurrency'),
        ('cartera', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=100, verbose_name='Monto')),
                ('description', models.TextField(default='', verbose_name='Descripción')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha del movimiento')),
                ('object_id', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=100, verbose_name='Precio')),
                ('movement', models.CharField(choices=[('BUY', 'buy'), ('SELL', 'sell')], max_length=4, verbose_name='Moviemiento')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='currencies.currency')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investment',
                'verbose_name_plural': 'Investment',
                'db_table': 'patrimoine_investments',
            },
            bases=(models.Model, src.general.mixins.BaseToAllMixin),
        ),
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=100, verbose_name='Monto')),
                ('description', models.TextField(default='', verbose_name='Descripción')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha del movimiento')),
                ('is_recurrent', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'patrimoine_saving',
            },
            bases=(models.Model, src.general.mixins.BaseToAllMixin),
        ),
        migrations.RemoveField(
            model_name='patrimonio',
            name='assets',
        ),
        migrations.RemoveField(
            model_name='patrimonio',
            name='default_currency',
        ),
        migrations.RemoveField(
            model_name='patrimonio',
            name='objectives',
        ),
        migrations.RemoveField(
            model_name='patrimonio',
            name='user',
        ),
        migrations.RemoveField(
            model_name='positionmovement',
            name='asset_related',
        ),
        migrations.RemoveField(
            model_name='positionmovement',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='positionmovement',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='income',
            options={},
        ),
        migrations.AlterModelOptions(
            name='spend',
            options={},
        ),
        migrations.RenameField(
            model_name='cashflowmovementcategory',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='cashflowmovementcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cashflowmovementcategory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashflow_movement_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialobjectif',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialobjectif',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='income',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='spend',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spend',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cashflowmovementcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='financialobjectif',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='income',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='income',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spend',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='spend',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='cashflowmovementcategory',
            table='patrimoine_cashflow_category',
        ),
        migrations.AlterModelTable(
            name='financialobjectif',
            table='patrimoine_objectives',
        ),
        migrations.AlterModelTable(
            name='income',
            table='patrimoine_income',
        ),
        migrations.AlterModelTable(
            name='spend',
            table='patrimoine_spend',
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='Patrimonio',
        ),
        migrations.DeleteModel(
            name='PositionMovement',
        ),
        migrations.AddField(
            model_name='saving',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cartera.cashflowmovementcategory'),
        ),
        migrations.AddField(
            model_name='saving',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='currencies.currency'),
        ),
        migrations.AddField(
            model_name='saving',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savings', to=settings.AUTH_USER_MODEL),
        ),
    ]
