# Generated by Django 3.2.16 on 2023-11-01 00:47

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import src.general.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('cartera', '0003_auto_20231001_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirsttradeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=100)),
                ('price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=100)),
                ('action', models.CharField(max_length=8)),
                ('description', models.CharField(max_length=100)),
                ('trade_date', models.DateField()),
                ('settled_date', models.DateField()),
                ('interest', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=100)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=100)),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=100)),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=100)),
                ('cusip', models.CharField(max_length=9)),
                ('record_type', models.CharField(max_length=9)),
                ('file_path', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Transaction from firstrade file',
                'verbose_name_plural': 'Transactions from firstrade file',
                'db_table': 'patrimoine_transactions_from_firstrade_file',
            },
            bases=(models.Model, src.general.mixins.BaseToAllMixin),
        ),
        migrations.AddField(
            model_name='income',
            name='transaction_file_id',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='transaction_file_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='investment',
            name='transaction_file_id',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='transaction_file_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='saving',
            name='transaction_file_id',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='saving',
            name='transaction_file_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='spend',
            name='transaction_file_id',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='spend',
            name='transaction_file_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='contenttypes.contenttype'),
        ),
    ]
