# Generated by Django 4.2.7 on 2023-11-01 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cartera", "0004_auto_20231101_0147"),
    ]

    operations = [
        migrations.AddField(
            model_name="firsttradetransaction",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="firstrade_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
