# Generated by Django 4.2.7 on 2023-11-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cartera", "0006_alter_firsttradetransaction_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firsttradetransaction",
            name="description",
            field=models.CharField(default="", max_length=300, null=True),
        ),
    ]
