# Generated by Django 4.2.7 on 2023-11-18 21:58

from decimal import Decimal
from django.db import migrations, models
import src.general.mixins


class Migration(migrations.Migration):
    dependencies = [
        ("cartera", "0007_alter_firsttradetransaction_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngEsTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("transaction_date", models.DateTimeField()),
                ("category", models.CharField(default="", max_length=300, null=True)),
                ("subcaterogy", models.CharField(default="", max_length=300, null=True)),
                ("comment", models.CharField(default="", max_length=300, null=True)),
                ("image", models.CharField(default="", max_length=300, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=100
                    ),
                ),
                ("file_path", models.CharField(max_length=100)),
                ("description", models.CharField(default="", max_length=300, null=True)),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=100
                    ),
                ),
            ],
            options={
                "db_table": "patrimoine_transactions_from_ing_es",
            },
            bases=(models.Model, src.general.mixins.BaseToAllMixin),
        ),
        migrations.AlterField(
            model_name="firsttradetransaction",
            name="cusip",
            field=models.CharField(default="", max_length=9, null=True),
        ),
    ]
