# Generated by Django 4.2.7 on 2023-11-18 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("currencies", "0002_userdefaultcurrency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cartera", "0008_ingestransaction_alter_firsttradetransaction_cusip"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingestransaction",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="currencies.currency",
            ),
        ),
        migrations.AddField(
            model_name="ingestransaction",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ing_es_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
