# Generated by Django 4.2.7 on 2023-12-24 13:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cartera", "0011_rename_amount_networth_equity_networth_incomes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firsttradetransaction",
            name="file_path",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="firsttradetransaction",
            name="price",
            field=models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=100),
        ),
        migrations.AlterField(
            model_name="firsttradetransaction",
            name="quantity",
            field=models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=100),
        ),
    ]
