# Generated by Django 4.2.7 on 2023-12-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cartera", "0012_alter_firsttradetransaction_file_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firsttradetransaction",
            name="description",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
    ]
