# Generated by Django 4.2.7 on 2023-12-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cartera", "0013_alter_firsttradetransaction_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firsttradetransaction",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="income",
            name="name",
            field=models.CharField(max_length=500, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="ingestransaction",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="ingestransaction",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="investment",
            name="name",
            field=models.CharField(max_length=500, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="savings",
            name="name",
            field=models.CharField(max_length=500, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="spendings",
            name="name",
            field=models.CharField(max_length=500, verbose_name="Nombre"),
        ),
    ]
