# Generated by Django 4.2.7 on 2023-12-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cartera", "0014_alter_firsttradetransaction_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investment",
            name="movement",
            field=models.CharField(
                choices=[
                    ("BUY", "buy"),
                    ("SELL", "sell"),
                    ("RECEIVE_FUND", "receive_fund"),
                    ("SEND_FUND", "send_fund"),
                ],
                max_length=12,
                verbose_name="Moviemiento",
            ),
        ),
    ]
