# Generated by Django 3.2.15 on 2022-08-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas_respuestas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hide_question',
            field=models.BooleanField(default=False),
        ),
    ]
