# Generated by Django 3.2.15 on 2022-10-16 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas_respuestas', '0003_question_extra_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='extra_data',
            new_name='checkings',
        ),
    ]
