# Generated by Django 3.2.16 on 2022-10-23 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas_respuestas', '0005_auto_20221017_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='preguntas_respuestas.question'),
        ),
    ]
