volumes:
  postgres_data: {}

services:
  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: invfin_local_postgres
    container_name: invfin_local_postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
      - ./backups:/backups:Z
    env_file:
      - ./.envs/.local/.postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5050:5050"

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: invfin_local_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
