# Generated by Django 3.2.15 on 2022-09-29 15:33

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seo', '0001_initial'),
        ('general', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialmedias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', ckeditor.fields.RichTextField()),
                ('sent', models.BooleanField(default=False)),
                ('date_to_send', models.DateTimeField(blank=True, null=True)),
                ('default_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='socialmedias.defaultcontent')),
                ('default_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='socialmedias.defaulttilte')),
                ('title_emojis', models.ManyToManyField(blank=True, to='socialmedias.Emoji')),
            ],
            options={
                'verbose_name': 'Emails by website',
                'db_table': 'website_emails',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteEmailsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=800)),
                ('slug', models.SlugField(blank=True, max_length=800, null=True)),
            ],
            options={
                'verbose_name': 'Emails type by website',
                'db_table': 'website_emails_type',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteLegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=800)),
                ('slug', models.SlugField(blank=True, max_length=800, null=True)),
                ('content', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Legal website pages',
                'db_table': 'website_pages_legals',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteEmailTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('opened', models.BooleanField(default=False)),
                ('date_opened', models.DateTimeField(default=django.utils.timezone.now)),
                ('email_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_related', to='web.websiteemail')),
                ('sent_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email counting',
                'db_table': 'website_emails_track',
            },
        ),
        migrations.AddField(
            model_name='websiteemail',
            name='type_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.websiteemailstype'),
        ),
        migrations.CreateModel(
            name='UserAndVisiteurCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=800)),
                ('slug', models.SlugField(blank=True, max_length=800, null=True)),
                ('name_for_user', models.CharField(blank=True, max_length=800, null=True)),
                ('show_to_user', models.BooleanField(default=False)),
                ('email_type_related', models.ManyToManyField(blank=True, to='web.WebsiteEmailsType')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('visiteurs', models.ManyToManyField(blank=True, to='seo.Visiteur')),
            ],
            options={
                'verbose_name': 'Category of users and visiteurs',
                'db_table': 'users_visiteurs_categories',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PromotionCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=600)),
                ('slug', models.SlugField(blank=True, max_length=800, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('categories', models.ManyToManyField(blank=True, to='general.Category')),
                ('email_type_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.websiteemailstype')),
                ('tags', models.ManyToManyField(blank=True, to='general.Tag')),
            ],
            options={
                'verbose_name': 'Promotions campaigns',
                'db_table': 'promotions_campaigns',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=600)),
                ('content', ckeditor.fields.RichTextField()),
                ('thumbnail', models.CharField(blank=True, max_length=600)),
                ('slug', models.SlugField(blank=True, max_length=800, null=True)),
                ('prize', models.PositiveBigIntegerField(default=0)),
                ('has_prize', models.BooleanField(default=False)),
                ('shareable_url', models.CharField(blank=True, max_length=600)),
                ('redirect_to', models.CharField(blank=True, max_length=600)),
                ('medium', models.CharField(blank=True, choices=[('ads', 'Ads'), ('email', 'Email'), ('invfin', 'Web'), ('social-media-posts', 'Social media posts')], max_length=250)),
                ('web_promotion_type', models.CharField(blank=True, choices=[('pop_up', 'Pop up'), ('banner', 'Big Banner'), ('lista', 'List'), ('solo', 'Solo')], max_length=250)),
                ('web_location', models.CharField(blank=True, choices=[('all-web', 'Toda la web'), ('web-inicio', 'Web Inicio'), ('screener-inicio', 'Screener Inicio'), ('screener-market', 'Screener Market'), ('screener-company', 'Screener Company'), ('cartera-inicio', 'Cartera Inicio'), ('cartera-financials', 'Cartera Financials'), ('cartera-balance', 'Cartera Balance'), ('private-profile', 'Private Profile'), ('public-profile', 'Public Profile'), ('question-inicio', 'Question Inicio'), ('question-details', 'Question Details'), ('term-inicio', 'Term Inicio'), ('term-details', 'Term Details'), ('blog-inicio', 'Blog Inicio'), ('blog-details', 'Blog Details')], max_length=250)),
                ('web_place', models.CharField(blank=True, choices=[('side', 'Side'), ('top', 'Top'), ('middle', 'Middle'), ('bottom', 'Bottom'), ('in_between', 'In between')], max_length=250)),
                ('social_media', models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('reddit', 'Reddit'), ('whatsapp', 'Whatsapp'), ('linkedin', 'Linkedin'), ('pinterest', 'Pinterest'), ('tumblr', 'Tumblr'), ('youtube', 'Youtube'), ('instagram', 'Instagram')], max_length=250)),
                ('publication_date', models.DateTimeField(blank=True)),
                ('reuse', models.BooleanField(default=False)),
                ('times_to_reuse', models.PositiveBigIntegerField(default=0)),
                ('clicks_by_user', models.PositiveBigIntegerField(default=0)),
                ('clicks_by_not_user', models.PositiveBigIntegerField(default=0)),
                ('campaign_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.promotioncampaign')),
                ('users_clicked', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('visiteurs_clicked', models.ManyToManyField(blank=True, to='seo.Visiteur')),
            ],
            options={
                'verbose_name': 'Promociones',
                'db_table': 'promotions',
            },
        ),
    ]
