# Generated by Django 3.2.15 on 2022-10-12 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20221008_0935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'verbose_name': 'Promotion'},
        ),
        migrations.AlterModelOptions(
            name='promotioncampaign',
            options={'verbose_name': 'Promotions campaign'},
        ),
        migrations.AlterModelOptions(
            name='userandvisiteurcategory',
            options={'ordering': ['-id'], 'verbose_name': 'Users and visiteurs category'},
        ),
        migrations.AlterModelOptions(
            name='websiteemail',
            options={'ordering': ['-id'], 'verbose_name': 'Email engagement'},
        ),
        migrations.AlterModelOptions(
            name='websiteemailstype',
            options={'ordering': ['-id'], 'verbose_name': 'Engagement emails type'},
        ),
        migrations.AlterModelOptions(
            name='websitelegalpage',
            options={'ordering': ['-id'], 'verbose_name': 'Legal website page'},
        ),
        migrations.RemoveField(
            model_name='promotioncampaign',
            name='email_type_related',
        ),
        migrations.AddField(
            model_name='promotioncampaign',
            name='type_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_campaigns', to='web.websiteemailstype'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='campaign_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='web.promotioncampaign'),
        ),
        migrations.AlterField(
            model_name='userandvisiteurcategory',
            name='email_type_related',
            field=models.ManyToManyField(blank=True, related_name='users_categories', to='web.WebsiteEmailsType'),
        ),
        migrations.AlterField(
            model_name='websiteemail',
            name='type_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_sent', to='web.websiteemailstype'),
        ),
    ]
