# Generated by Django 3.2.15 on 2022-10-16 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('web', '0003_auto_20221012_0959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websiteemail',
            options={'ordering': ['-id'], 'verbose_name': 'Website emails'},
        ),
        migrations.AlterModelOptions(
            name='websiteemailstype',
            options={'ordering': ['-id'], 'verbose_name': 'Website emails type'},
        ),
        migrations.AddField(
            model_name='websiteemail',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='websiteemail',
            name='object_id',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
