# Generated by Django 3.2.15 on 2022-10-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0004_auto_20221016_0939"),
    ]

    operations = [
        migrations.AddField(
            model_name="websiteemail",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="websiteemail",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="websiteemailtrack",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="websiteemailtrack",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
