# Generated by Django 3.2.14 on 2022-07-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20220727_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteemailstype',
            name='slug',
            field=models.SlugField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='slug',
            field=models.SlugField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='promotioncampaign',
            name='slug',
            field=models.SlugField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='websitelegalpage',
            name='slug',
            field=models.SlugField(blank=True, max_length=800, null=True),
        ),
    ]
