# Generated by Django 3.2.15 on 2022-10-27 07:03

import apps.general.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20221017_2321'),
        ('web', '0005_auto_20221017_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=600)),
                ('slug', models.SlugField(blank=True, max_length=800, null=True)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('categories', models.ManyToManyField(blank=True, to='general.Category')),
                ('tags', models.ManyToManyField(blank=True, to='general.Tag')),
            ],
            options={
                'verbose_name': 'Campaign',
                'db_table': 'campaigns',
            },
            bases=(models.Model, apps.general.mixins.BaseToAllMixin),
        ),
        migrations.RemoveField(
            model_name='userandvisiteurcategory',
            name='email_type_related',
        ),
        migrations.RemoveField(
            model_name='userandvisiteurcategory',
            name='users',
        ),
        migrations.RemoveField(
            model_name='userandvisiteurcategory',
            name='visiteurs',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='web_promotion_type',
            new_name='web_promotion_style',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='campaign_related',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='has_prize',
        ),
        migrations.RemoveField(
            model_name='websiteemail',
            name='type_related',
        ),
        migrations.AlterField(
            model_name='promotion',
            name='medium',
            field=models.CharField(choices=[('ads', 'Ads'), ('email', 'Email'), ('web', 'Web'), ('social-media-posts', 'Social media posts')], default='web', max_length=250),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='redirect_to',
            field=models.SlugField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='shareable_url',
            field=models.SlugField(blank=True, max_length=600),
        ),
        migrations.DeleteModel(
            name='PromotionCampaign',
        ),
        migrations.DeleteModel(
            name='UserAndVisiteurCategory',
        ),
        migrations.DeleteModel(
            name='WebsiteEmailsType',
        ),
        migrations.AddField(
            model_name='promotion',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='web.campaign'),
        ),
        migrations.AddField(
            model_name='websiteemail',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='web.campaign'),
        ),
    ]
