# Generated by Django 3.2.14 on 2022-08-01 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seo', '0013_auto_20220727_2237'),
        ('web', '0006_auto_20220728_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotioncampaign',
            name='email_type_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.websiteemailstype'),
        ),
        migrations.CreateModel(
            name='UserAndVisiteurCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=800)),
                ('slug', models.SlugField(blank=True, max_length=800, null=True)),
                ('name_for_user', models.CharField(blank=True, max_length=800, null=True)),
                ('show_to_user', models.BooleanField(default=False)),
                ('email_type_related', models.ManyToManyField(blank=True, to='web.WebsiteEmailsType')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('visiteurs', models.ManyToManyField(blank=True, to='seo.Visiteur')),
            ],
            options={
                'verbose_name': 'Category of users and visiteurs',
                'db_table': 'users_visiteurs_categories',
                'ordering': ['-id'],
            },
        ),
    ]
