# Generated by Django 3.2.15 on 2022-08-11 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('escritos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='termrequestapi',
            name='search',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='escritos.term'),
        ),
    ]
