# Generated by Django 3.2.15 on 2022-11-04 22:43

import src.general.mixins
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DefaultContent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=500)),
                (
                    "for_content",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (0, "All"),
                            (1, "Question"),
                            (2, "News"),
                            (3, "Term"),
                            (4, "PublicBlog"),
                            (5, "Company"),
                            (6, "Web"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("promotion", "Promotion"),
                            ("suggestion", "Suggestion"),
                            ("announcement", "Announcement"),
                            ("welcome", "Welcome"),
                            ("engagement", "Engagement"),
                            ("newsletter", "Newsletter"),
                            ("engagement-user-no-active", "Engagement user no active"),
                            ("engagement-user-little-active", "Engagement user little active"),
                            ("engagement-user-first-call", "Engagement user first call"),
                            ("newsletter-blog", "Newsletter for blog"),
                            ("newsletter-public-blog", "Newsletter  for public blog"),
                            ("newsletter-term", "Newsletter for term"),
                            ("newsletter-company", "Newsletter for company"),
                            ("newsletter-company-news", "Newsletter for company news"),
                            ("newsletter-company-report", "Newsletter for company report"),
                        ],
                        max_length=500,
                        null=True,
                    ),
                ),
                ("content", ckeditor.fields.RichTextField()),
            ],
            options={
                "verbose_name": "Default content",
                "db_table": "socialmedia_content",
            },
            bases=(models.Model, src.general.mixins.BaseToAllMixin),
        ),
        migrations.CreateModel(
            name="DefaultTilte",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.TextField(default="")),
                (
                    "for_content",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (0, "All"),
                            (1, "Question"),
                            (2, "News"),
                            (3, "Term"),
                            (4, "PublicBlog"),
                            (5, "Company"),
                            (6, "Web"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("promotion", "Promotion"),
                            ("suggestion", "Suggestion"),
                            ("announcement", "Announcement"),
                            ("welcome", "Welcome"),
                            ("engagement", "Engagement"),
                            ("newsletter", "Newsletter"),
                            ("engagement-user-no-active", "Engagement user no active"),
                            ("engagement-user-little-active", "Engagement user little active"),
                            ("engagement-user-first-call", "Engagement user first call"),
                            ("newsletter-blog", "Newsletter for blog"),
                            ("newsletter-public-blog", "Newsletter  for public blog"),
                            ("newsletter-term", "Newsletter for term"),
                            ("newsletter-company", "Newsletter for company"),
                            ("newsletter-company-news", "Newsletter for company news"),
                            ("newsletter-company-report", "Newsletter for company report"),
                        ],
                        max_length=500,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Default titles",
                "db_table": "socialmedia_titles",
            },
            bases=(models.Model, src.general.mixins.BaseToAllMixin),
        ),
        migrations.CreateModel(
            name="Emoji",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("emoji", models.CharField(max_length=500)),
            ],
            options={
                "verbose_name": "Default emojis",
                "db_table": "socialmedia_emojis",
            },
            bases=(models.Model, src.general.mixins.BaseToAllMixin),
        ),
        migrations.CreateModel(
            name="Hashtag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.TextField(default="")),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("twitter", "Twitter"),
                            ("reddit", "Reddit"),
                            ("whatsapp", "Whatsapp"),
                            ("linkedin", "Linkedin"),
                            ("pinterest", "Pinterest"),
                            ("tumblr", "Tumblr"),
                            ("youtube", "Youtube"),
                            ("instagram", "Instagram"),
                        ],
                        max_length=500,
                    ),
                ),
                ("is_trending", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Default hashtags",
                "db_table": "socialmedia_hashtags",
            },
            bases=(models.Model, src.general.mixins.BaseToAllMixin),
        ),
    ]
