# Generated by Django 4.2.7 on 2023-11-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("countries", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="alpha_2_code",
            field=models.CharField(blank=True, default="", max_length=2),
        ),
        migrations.AlterField(
            model_name="country",
            name="alpha_3_code",
            field=models.CharField(blank=True, default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="country",
            name="country",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="country",
            name="iso",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="country",
            name="spanish_name",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
