# Generated by Django 3.2.16 on 2023-03-19 23:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='termcorrection',
            name='original_content',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='termcorrection',
            name='original_title',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='termcorrection',
            name='content',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='termcorrection',
            name='title',
            field=models.CharField(blank=True, default='', max_length=3000),
        ),
    ]
