# Generated by Django 3.2.15 on 2022-11-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='slug',
            field=models.SlugField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='title',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
