# Generated by Django 3.2.18 on 2023-03-21 20:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritos', '0003_auto_20230320_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termcorrection',
            name='original_content',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='termcorrection',
            name='original_title',
            field=models.CharField(blank=True, default='', max_length=3000),
        ),
    ]
