# Generated by Django 3.2.16 on 2023-03-21 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escritos', '0004_auto_20230321_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='termcorrection',
            old_name='reviwed_by',
            new_name='corrected_by',
        ),
    ]
