# Generated by Django 3.2.16 on 2022-12-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_blog', '0003_auto_20221130_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicblogasnewsletter',
            name='call_to_action',
            field=models.CharField(default='', max_length=500),
        ),
    ]
