# Generated by Django 3.2.16 on 2022-12-26 14:48

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def move_writer_profile(apps, schema):
    WriterProfile = apps.get_model("public_blog", "WriterProfile")
    WritterProfile = apps.get_model("public_blog", "WritterProfile")
    for writer in WritterProfile.objects.values():
        writer.pop("id")
        writer["instagram"] = writer.pop("insta")
        WriterProfile.objects.create(**writer)


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("public_blog", "0006_auto_20221216_2036"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletterfollowers",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="main_writer_followed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterModelTable(
            name="followinghistorial",
            table="writer_followers_historial",
        ),
        migrations.AlterModelTable(
            name="newsletterfollowers",
            table="writer_followers_newsletters",
        ),
        migrations.CreateModel(
            name="WriterProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("host_name", models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ("long_description", ckeditor.fields.RichTextField(default="", blank=True)),
                ("facebook", models.CharField(blank=True, max_length=500, null=True)),
                ("twitter", models.CharField(blank=True, max_length=500, null=True)),
                ("instagram", models.CharField(blank=True, max_length=500, null=True)),
                ("youtube", models.CharField(blank=True, max_length=500, null=True)),
                ("linkedin", models.CharField(blank=True, max_length=500, null=True)),
                ("tiktok", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="writer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User writer profile",
                "db_table": "writer_profile",
            },
        ),
        migrations.RunPython(move_writer_profile),
        migrations.DeleteModel(
            name="WritterProfile",
        ),
    ]
