PERIOD_1_QUARTER = 1
PERIOD_2_QUARTER = 2
PERIOD_3_QUARTER = 3
PERIOD_4_QUARTER = 4
PERIOD_FOR_YEAR = 5

QUARTER_PER_MONTH = {
    1: PERIOD_1_QUARTER,
    2: PERIOD_1_QUARTER,
    3: PERIOD_1_QUARTER,
    4: PERIOD_2_QUARTER,
    5: PERIOD_2_QUARTER,
    6: PERIOD_2_QUARTER,
    7: PERIOD_3_QUARTER,
    8: PERIOD_3_QUARTER,
    9: PERIOD_3_QUARTER,
    10: PERIOD_4_QUARTER,
    11: PERIOD_4_QUARTER,
    12: PERIOD_4_QUARTER,
}

PERIODS_QUARTERS = (
    (PERIOD_1_QUARTER, "1 Quarter"),
    (PERIOD_2_QUARTER, "2 Quarter"),
    (PERIOD_3_QUARTER, "3 Quarter"),
    (PERIOD_4_QUARTER, "4 Quarter"),
)

PERIODS = (
    *PERIODS_QUARTERS,
    (PERIOD_FOR_YEAR, "For Year"),
)
