# Generated by Django 3.2.12 on 2022-08-11 18:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('slug', models.CharField(blank=True, max_length=500, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=500, null=True)),
                ('iso', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'assets_countries',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(blank=True, max_length=500, null=True)),
                ('symbol', models.CharField(blank=True, max_length=5, null=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('iso', models.CharField(blank=True, max_length=500, null=True)),
                ('decimals', models.IntegerField(blank=True, default=2)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'db_table': 'assets_currencies',
            },
        ),
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('opened', models.BooleanField(default=False)),
                ('date_opened', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Email from notifications',
                'db_table': 'emails_notifications',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(blank=True, max_length=500, null=True)),
                ('industry_spanish', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Industry',
                'verbose_name_plural': 'Industries',
                'db_table': 'assets_industries',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField(blank=True, null=True)),
                ('period', models.IntegerField(blank=True, choices=[(1, '1 Quarter'), (2, '2 Quarter'), (3, '3 Quarter'), (4, '4 Quarter')], null=True)),
            ],
            options={
                'verbose_name': 'Period',
                'verbose_name_plural': 'Periods',
                'db_table': 'assets_periods',
                'ordering': ['-year', '-period'],
                'get_latest_by': ['-year', '-period'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(blank=True, max_length=500, null=True)),
                ('sector_spanish', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectors',
                'db_table': 'assets_sectors',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('slug', models.CharField(blank=True, max_length=500, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('notification_type', models.CharField(choices=[('Nuevo blog', 'Nuevo blog'), ('Nuevo comentario', 'Nuevo comentario'), ('Nuevo voto', 'Nuevo voto'), ('Nuevo seguidor', 'Nuevo seguidor'), ('Nueva pregunta', 'Nueva pregunta'), ('Nueva respuesta', 'Nueva respuesta'), ('Respuesta aceptada', 'Respuesta aceptada'), ('Compra efectuada', 'Compra efectuada'), ('Comenta tu úlitma compra', '¿Qué opinas de tu última compra?')], max_length=500)),
                ('is_seen', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Notification',
                'db_table': 'notifications',
            },
        ),
    ]
