# Generated by Django 3.2.15 on 2022-08-14 15:17

from django.db import migrations, models


def update_periods(apps, schema):
    Period = apps.get_model('general', 'period')
    for period in Period.objects.all():
        period.for_year = int(period.year.year)
        period.save(update_fields=["for_year"])


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='for_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='period',
            field=models.IntegerField(blank=True, choices=[(1, '1 Quarter'), (2, '2 Quarter'), (3, '3 Quarter'), (4, '4 Quarter'), (5, 'For Yyear')], null=True),
        ),
        migrations.RunPython(update_periods),
        migrations.RemoveField(
            model_name='period',
            name='year',
        ),
        migrations.RenameField(
            model_name='period',
            old_name='for_year',
            new_name='year',
        ),
    ]
