# Generated by Django 3.2.15 on 2022-08-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20220814_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='period',
            field=models.IntegerField(blank=True, choices=[(1, '1 Quarter'), (2, '2 Quarter'), (3, '3 Quarter'), (4, '4 Quarter'), (5, 'For Year')], null=True),
        ),
    ]
