# Generated by Django 3.2.15 on 2022-09-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='alpha_2_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='alpha_3_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
