# Generated by Django 3.2.15 on 2022-09-03 09:24
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_auto_20220902_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='country',
        ),
        migrations.AddField(
            model_name='currency',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='currency', to='general.Country'),
        ),
        migrations.AddField(
            model_name='country',
            name='spanish_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='spanish_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),

        migrations.AddField(
            model_name='currency',
            name='accronym',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
