EMAIL_FOR_PUBLIC_BLOG = "public_blog"
EMAIL_FOR_NOTIFICATION = "notification"
EMAIL_FOR_WEB = "web"

PIXEL_GIF_BYTES = b"iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII="
