# Generated by Django 3.2.16 on 2022-12-26 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221217_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_writter',
            new_name='is_writer',
        ),
    ]
