# Generated by Django 3.2.15 on 2022-08-18 17:28

import apps.business.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomplementary',
            name='extras',
            field=models.JSONField(default=apps.business.models.default_dict),
        ),
    ]
