# Generated by Django 4.2.7 on 2023-11-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("industries_sectors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="industry",
            name="industry",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="industry",
            name="industry_spanish",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="sector",
            name="sector",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="sector",
            name="sector_spanish",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
