PERIOD_1_QUARTER = 1
PERIOD_2_QUARTER = 2
PERIOD_3_QUARTER = 3
PERIOD_4_QUARTER = 4
PERIOD_FOR_YEAR = 5

PERIODS_QUARRTERS = (
    (PERIOD_1_QUARTER, "1 Quarter"),
    (PERIOD_2_QUARTER, "2 Quarter"),
    (PERIOD_3_QUARTER, "3 Quarter"),
    (PERIOD_4_QUARTER, "4 Quarter"),
)

PERIODS = (
    *PERIODS_QUARRTERS,
    (PERIOD_FOR_YEAR, "For Year"),
)
