# Generated by Django 3.2.15 on 2022-11-18 20:01

import apps.empresas.extensions.as_reported
import apps.general.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('periods', '0002_auto_20221105_2044'),
        ('currencies', '0002_auto_20221105_2044'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAsReportedProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('empresas.company',),
        ),
        migrations.CreateModel(
            name='StatementItemConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concept', models.CharField(max_length=2000)),
                ('label', models.CharField(max_length=2000)),
                ('concept_slug', models.CharField(max_length=2000)),
                ('label_slug', models.CharField(max_length=2000)),
                ('notes', models.TextField(default='', null=True)),
                ('tooltip', models.TextField(default='', null=True)),
                ('definition_path', models.SlugField(max_length=350)),
                ('corresponding_final_item', models.CharField(default='', max_length=350, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unique_statements_items', to='empresas.company')),
            ],
            options={
                'db_table': 'assets_as_repoted_statements_items_concepts',
            },
            bases=(models.Model, apps.general.mixins.BaseToAllMixin),
        ),
        migrations.CreateModel(
            name='StatementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.statementitemconcept')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='currencies.currency')),
            ],
            options={
                'db_table': 'assets_as_repoted_statements_items',
            },
            bases=(models.Model, apps.general.mixins.BaseToAllMixin),
        ),
        migrations.CreateModel(
            name='IncomeStatementAsReported',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.IntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('financial_data', models.JSONField()),
                ('from_file', models.CharField(default='', max_length=250, null=True)),
                ('from_folder', models.CharField(default='', max_length=250, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inc_statements_as_reported', to='empresas.company')),
                ('fields', models.ManyToManyField(blank=True, to='empresas.StatementItem')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='periods.period')),
                ('reported_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='currencies.currency')),
            ],
            options={
                'db_table': 'assets_income_statement_as_reported',
            },
            bases=(models.Model, apps.general.mixins.BaseToAllMixin, apps.empresas.extensions.as_reported.IncomeStatementAsReportedExtended),
        ),
        migrations.CreateModel(
            name='CashflowStatementAsReported',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.IntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('financial_data', models.JSONField()),
                ('from_file', models.CharField(default='', max_length=250, null=True)),
                ('from_folder', models.CharField(default='', max_length=250, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cf_statements_as_reported', to='empresas.company')),
                ('fields', models.ManyToManyField(blank=True, to='empresas.StatementItem')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='periods.period')),
                ('reported_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='currencies.currency')),
            ],
            options={
                'db_table': 'assets_cashflow_statement_as_reported',
            },
            bases=(models.Model, apps.general.mixins.BaseToAllMixin),
        ),
        migrations.CreateModel(
            name='BalanceSheetAsReported',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.IntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('financial_data', models.JSONField()),
                ('from_file', models.CharField(default='', max_length=250, null=True)),
                ('from_folder', models.CharField(default='', max_length=250, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_sheets_as_reported', to='empresas.company')),
                ('fields', models.ManyToManyField(blank=True, to='empresas.StatementItem')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='periods.period')),
                ('reported_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='currencies.currency')),
            ],
            options={
                'db_table': 'assets_balance_sheet_as_reported',
            },
            bases=(models.Model, apps.general.mixins.BaseToAllMixin),
        ),
    ]
