# Generated by Django 3.2.15 on 2022-11-08 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_balancesheetasreported_cashflowstatementasreported_incomestatementasreported'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAsReportedProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('empresas.company',),
        ),
    ]
