# Generated by Django 3.2.15 on 2022-08-11 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balancesheet',
            old_name='deferredRevenue',
            new_name='deferred_revenue',
        ),
        migrations.RenameField(
            model_name='balancesheet',
            old_name='shortTermDebt',
            new_name='short_term_debt',
        ),
        migrations.RenameField(
            model_name='balancesheet',
            old_name='taxPayables',
            new_name='tax_payables',
        ),
        migrations.RenameField(
            model_name='operationriskratio',
            old_name='cashFlowCoverageRatios',
            new_name='cash_flow_coverage_ratios',
        ),
        migrations.RenameField(
            model_name='operationriskratio',
            old_name='debtRatio',
            new_name='debt_ratio',
        ),
        migrations.RenameField(
            model_name='operationriskratio',
            old_name='interestCoverage',
            new_name='interest_coverage',
        ),
        migrations.RenameField(
            model_name='operationriskratio',
            old_name='longTermDebtToCapitalization',
            new_name='long_term_debt_to_capitalization',
        ),
        migrations.RenameField(
            model_name='operationriskratio',
            old_name='totalDebtToCapitalization',
            new_name='total_debt_to_capitalization',
        ),
        migrations.RenameField(
            model_name='rentabilityratio',
            old_name='nopatroic',
            new_name='nopat_roic',
        ),
    ]
