# Generated by Django 3.2.15 on 2022-11-08 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_companyasreportedproxy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incomestatementasreported',
            options={'ordering': ['-date', 'period']},
        ),
    ]
