# Generated by Django 3.2.15 on 2022-08-18 17:28

import apps.empresas.models.base
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_remove_company_data_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='accounts_payable',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='accounts_receivable',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='accumulated_depreciation',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='as_of_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='available_for_sale_securities',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='capital_stock',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='cash_and_cash_equivalents',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='cash_cash_equivalents_and_short_term_investments',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='cash_equivalents',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='cash_financial',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='commercial_paper',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='common_stock',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='common_stock_equity',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='currency_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='current_assets',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='current_debt',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='current_debt_and_capital_lease_obligation',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='current_deferred_liabilities',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='current_deferred_revenue',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='current_liabilities',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='gains_losses_not_affecting_retained_earnings',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='gross_ppe',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='inventory',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='invested_capital',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='investmentin_financial_assets',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='investments_and_advances',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='land_and_improvements',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='leases',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='long_term_debt',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='long_term_debt_and_capital_lease_obligation',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='machinery_furniture_equipment',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='net_debt',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='net_ppe',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='net_tangible_assets',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='non_current_deferred_liabilities',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='non_current_deferred_revenue',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='non_current_deferred_taxes_liabilities',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='ordinary_shares_number',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='other_current_assets',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='other_current_borrowings',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='other_current_liabilities',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='other_non_current_assets',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='other_non_current_liabilities',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='other_receivables',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='other_short_term_investments',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='payables',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='payables_and_accrued_expenses',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='period_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='properties',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='receivables',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='retained_earnings',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='share_issued',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='stockholders_equity',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='tangible_book_value',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='total_assets',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='total_capitalization',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='total_debt',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='total_equity_gross_minority_interest',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='total_liabilities_net_minority_interest',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='total_non_current_assets',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='total_non_current_liabilities_net_minority_interest',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='tradeand_other_payables_non_current',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyahooquery',
            name='working_capital',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='as_of_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='beginning_cash_position',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='capital_expenditure',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='cash_dividends_paid',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='cash_flow_from_continuing_financing_activities',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='cash_flow_from_continuing_investing_activities',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='cash_flow_from_continuing_operating_activities',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='change_in_account_payable',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='change_in_cash_supplemental_as_reported',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='change_in_inventory',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='change_in_other_current_assets',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='change_in_other_current_liabilities',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='change_in_other_working_capital',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='change_in_payable',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='change_in_payables_and_accrued_expense',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='change_in_receivables',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='change_in_working_capital',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='changes_in_account_receivables',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='changes_in_cash',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='common_stock_dividend_paid',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='common_stock_issuance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='common_stock_payments',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='currency_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='deferred_income_tax',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='deferred_tax',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='depreciation_amortization_depletion',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='depreciation_and_amortization',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='end_cash_position',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='financing_cash_flow',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='free_cash_flow',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='income_tax_paid_supplemental_data',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='interest_paid_supplemental_data',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='investing_cash_flow',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='issuance_of_capital_stock',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='issuance_of_debt',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='long_term_debt_issuance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='long_term_debt_payments',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='net_business_purchase_and_sale',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='net_common_stock_issuance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='net_income',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='net_income_from_continuing_operations',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='net_investment_purchase_and_sale',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='net_issuance_payments_of_debt',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='net_long_term_debt_issuance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='net_other_financing_charges',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='net_other_investing_changes',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='net_ppe_purchase_and_sale',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='net_short_term_debt_issuance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='operating_cash_flow',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='other_non_cash_items',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='period_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='purchase_of_business',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='purchase_of_investment',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='purchase_of_ppe',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='repayment_of_debt',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='repurchase_of_capital_stock',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='sale_of_investment',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='short_term_debt_payments',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyahooquery',
            name='stock_based_compensation',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyahooquery',
            name='as_of_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyahooquery',
            name='basic_average_shares',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyahooquery',
            name='basic_eps',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyahooquery',
            name='cost_of_revenue',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyahooquery',
            name='currency_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyahooquery',
            name='diluted_average_shares',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyahooquery',
            name='diluted_eps',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyahooquery',
            name='diluted_ni_availto_com_stockholders',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyahooquery',
            name='ebit',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyahooquery',
            name='ebitda',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyahooquery',
            name='gross_profit',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyahooquery',
            name='interest_expense',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyahooquery',
            name='interest_expense_non_operating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyahooquery',
            name='interest_income',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyahooquery',
            name='interest_income_non_operating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyahooquery',
            name='net_income',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyahooquery',
            name='net_income_common_stockholders',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyahooquery',
            name='net_income_continuous_operations',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyahooquery',
            name='net_income_from_continuing_and_discontinued_operation',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyahooquery',
            name='net_income_from_continuing_operation_net_minority_interest',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyahooquery',
            name='net_income_including_noncontrolling_interests',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyahooquery',
            name='net_interest_income',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyahooquery',
            name='net_non_operating_interest_income_expense',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyahooquery',
            name='normalized_ebitda',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyahooquery',
            name='normalized_income',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyahooquery',
            name='operating_expense',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyahooquery',
            name='operating_income',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyahooquery',
            name='operating_revenue',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyahooquery',
            name='other_income_expense',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyahooquery',
            name='other_non_operating_income_expenses',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyahooquery',
            name='period_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyahooquery',
            name='pretax_income',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyahooquery',
            name='reconciled_cost_of_revenue',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyahooquery',
            name='reconciled_depreciation',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyahooquery',
            name='research_and_development',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyahooquery',
            name='selling_general_and_administration',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyahooquery',
            name='tax_effect_of_unusual_items',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyahooquery',
            name='tax_provision',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyahooquery',
            name='tax_rate_for_calcs',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyahooquery',
            name='total_expenses',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyahooquery',
            name='total_operating_income_as_reported',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyahooquery',
            name='total_revenue',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheetyahooquery',
            name='financials',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='balancesheetyfinance',
            name='financials',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='cashflowstatementyahooquery',
            name='financials',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='cashflowstatementyfinance',
            name='financials',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='company',
            name='checkings',
            field=models.JSONField(default=apps.empresas.models.base.default_dict),
        ),
        migrations.AlterField(
            model_name='incomestatementyahooquery',
            name='financials',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='incomestatementyfinance',
            name='financials',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='statementsfinnhub',
            name='financials',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='KeyStatsYahooQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(default=0)),
                ('year', models.DateField(blank=True, null=True)),
                ('financials', models.JSONField(default=dict)),
                ('max_age', models.FloatField(blank=True, default=0, null=True)),
                ('price_hint', models.FloatField(blank=True, default=0, null=True)),
                ('enterprise_value', models.FloatField(blank=True, default=0, null=True)),
                ('forward_pe', models.FloatField(blank=True, default=0, null=True)),
                ('profit_margins', models.FloatField(blank=True, default=0, null=True)),
                ('float_shares', models.FloatField(blank=True, default=0, null=True)),
                ('shares_outstanding', models.FloatField(blank=True, default=0, null=True)),
                ('shares_short', models.FloatField(blank=True, default=0, null=True)),
                ('shares_short_prior_month', models.FloatField(blank=True, default=0, null=True)),
                ('shares_short_previous_month_date', models.DateField(blank=True, null=True)),
                ('date_short_interest', models.DateField(blank=True, null=True)),
                ('shares_percent_shares_out', models.FloatField(blank=True, default=0, null=True)),
                ('held_percent_insiders', models.FloatField(blank=True, default=0, null=True)),
                ('held_percent_institutions', models.FloatField(blank=True, default=0, null=True)),
                ('short_ratio', models.FloatField(blank=True, default=0, null=True)),
                ('short_percent_of_float', models.FloatField(blank=True, default=0, null=True)),
                ('beta', models.FloatField(blank=True, default=0, null=True)),
                ('category', models.FloatField(blank=True, default=0, null=True)),
                ('book_value', models.FloatField(blank=True, default=0, null=True)),
                ('price_to_book', models.FloatField(blank=True, default=0, null=True)),
                ('fund_family', models.FloatField(blank=True, default=0, null=True)),
                ('legal_type', models.FloatField(blank=True, default=0, null=True)),
                ('last_fiscal_year_end', models.DateField(blank=True, null=True)),
                ('next_fiscal_year_end', models.DateField(blank=True, null=True)),
                ('most_recent_quarter', models.DateField(blank=True, null=True)),
                ('earnings_quarterly_growth', models.FloatField(blank=True, default=0, null=True)),
                ('net_income_to_common', models.FloatField(blank=True, default=0, null=True)),
                ('trailing_eps', models.FloatField(blank=True, default=0, null=True)),
                ('forward_eps', models.FloatField(blank=True, default=0, null=True)),
                ('peg_ratio', models.FloatField(blank=True, default=0, null=True)),
                ('last_split_factor', models.CharField(blank=True, max_length=10, null=True)),
                ('last_split_date', models.DateField(blank=True, null=True)),
                ('enterprise_to_revenue', models.FloatField(blank=True, default=0, null=True)),
                ('enterprise_to_ebitda', models.FloatField(blank=True, default=0, null=True)),
                ('week_change_52', models.FloatField(blank=True, default=0, null=True)),
                ('sand_p52_week_change', models.FloatField(blank=True, default=0, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresas.company')),
            ],
            options={
                'verbose_name': 'Yahooquery Key stats',
                'verbose_name_plural': 'Yahooquery Key stats',
                'db_table': 'assets_companies_key stats_yahooquery',
                'ordering': ['-date'],
                'get_latest_by': 'date',
                'abstract': False,
            },
        ),
    ]
