# Generated by Django 3.2.15 on 2022-08-28 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0008_auto_20220818_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFinprepProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('empresas.company',),
        ),
        migrations.CreateModel(
            name='CompanyYahooQueryProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('empresas.company',),
        ),
        migrations.CreateModel(
            name='CompanyYFinanceProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('empresas.company',),
        ),
    ]
