# Generated by Django 3.2.15 on 2022-08-30 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0009_companyfinprepproxy_companyyahooqueryproxy_companyyfinanceproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFinnhubProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('empresas.company',),
        ),
        migrations.CreateModel(
            name='CompanyStatementsProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('empresas.company',),
        ),
    ]
