# Generated by Django 3.2.15 on 2022-08-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0010_companyfinnhubproxy_companystatementsproxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keystatsyahooquery',
            name='date_short_interest',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='keystatsyahooquery',
            name='last_fiscal_year_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='keystatsyahooquery',
            name='last_split_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='keystatsyahooquery',
            name='most_recent_quarter',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='keystatsyahooquery',
            name='next_fiscal_year_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='keystatsyahooquery',
            name='shares_short_previous_month_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
