# Generated by Django 3.2.15 on 2022-09-25 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_auto_20220903_1124'),
        ('empresas', '0011_auto_20220831_2115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balancesheet',
            options={'get_latest_by': ['-date', 'period'], 'ordering': ['-date', 'period'], 'verbose_name': 'Balance Sheet', 'verbose_name_plural': 'Balance Sheets'},
        ),
        migrations.AlterModelOptions(
            name='balancesheetfinprep',
            options={'get_latest_by': ['-date', 'period'], 'ordering': ['-date', 'period'], 'verbose_name': 'Finprep Balance Sheet', 'verbose_name_plural': 'Finprep Balance Sheets'},
        ),
        migrations.AlterModelOptions(
            name='balancesheetyahooquery',
            options={'get_latest_by': ['-date', 'period'], 'ordering': ['-date', 'period'], 'verbose_name': 'Yahooquery Balance Sheet', 'verbose_name_plural': 'Yahooquery Balance Sheets'},
        ),
        migrations.AlterModelOptions(
            name='balancesheetyfinance',
            options={'get_latest_by': ['-date', 'period'], 'ordering': ['-date', 'period'], 'verbose_name': 'YFinance Balance Sheet', 'verbose_name_plural': 'YFinance Balance Sheets'},
        ),
        migrations.AlterModelOptions(
            name='cashflowstatement',
            options={'get_latest_by': ['-date', 'period'], 'ordering': ['-date', 'period'], 'verbose_name': 'Cash flow Statement', 'verbose_name_plural': 'Cash flow Statements'},
        ),
        migrations.AlterModelOptions(
            name='cashflowstatementfinprep',
            options={'get_latest_by': ['-date', 'period'], 'ordering': ['-date', 'period'], 'verbose_name': 'Finprep Cash flow Statement', 'verbose_name_plural': 'Finprep Cash flow Statements'},
        ),
        migrations.AlterModelOptions(
            name='cashflowstatementyahooquery',
            options={'get_latest_by': ['-date', 'period'], 'ordering': ['-date', 'period'], 'verbose_name': 'Yahooquery Cash flow Statement', 'verbose_name_plural': 'Yahooquery Cash flow Statements'},
        ),
        migrations.AlterModelOptions(
            name='cashflowstatementyfinance',
            options={'get_latest_by': ['-date', 'period'], 'ordering': ['-date', 'period'], 'verbose_name': 'YFinance Cash flow Statement', 'verbose_name_plural': 'YFinance Cash flow Statements'},
        ),
        migrations.AlterModelOptions(
            name='companygrowth',
            options={'get_latest_by': ['-date', 'period'], 'ordering': ['-date', 'period'], 'verbose_name': 'Company growth', 'verbose_name_plural': 'Companies growth'},
        ),
        migrations.AlterModelOptions(
            name='eficiencyratio',
            options={'get_latest_by': ['-date', 'period'], 'ordering': ['-date', 'period'], 'verbose_name': 'Efficiency Ratio', 'verbose_name_plural': 'Efficiency Ratios'},
        ),
        migrations.AlterModelOptions(
            name='enterprisevalueratio',
            options={'get_latest_by': ['-date', 'period'], 'ordering': ['-date', 'period'], 'verbose_name': 'Enterprise Value', 'verbose_name_plural': 'Enterprise Values'},
        ),
        migrations.AlterModelOptions(
            name='freecashflowratio',
            options={'get_latest_by': ['-date', 'period'], 'ordering': ['-date', 'period'], 'verbose_name': 'Free cash flow Ratio', 'verbose_name_plural': 'Free cash flow Ratios'},
        ),
        migrations.AlterModelOptions(
            name='incomestatement',
            options={'get_latest_by': ['-date', 'period'], 'ordering': ['-date', 'period'], 'verbose_name': 'Income Statement', 'verbose_name_plural': 'Income Statements'},
        ),
        migrations.AlterModelOptions(
            name='incomestatementfinprep',
            options={'get_latest_by': ['-date', 'period'], 'ordering': ['-date', 'period'], 'verbose_name': 'Finprep Income Statement', 'verbose_name_plural': 'Finprep Income Statements'},
        ),
        migrations.AlterModelOptions(
            name='incomestatementyahooquery',
            options={'get_latest_by': ['-date', 'period'], 'ordering': ['-date', 'period'], 'verbose_name': 'Yahooquery Income Statement', 'verbose_name_plural': 'Yahooquery Income Statements'},
        ),
        migrations.AlterModelOptions(
            name='incomestatementyfinance',
            options={'get_latest_by': ['-date', 'period'], 'ordering': ['-date', 'period'], 'verbose_name': 'YFinance Income Statement', 'verbose_name_plural': 'YFinance Income Statements'},
        ),
        migrations.AlterModelOptions(
            name='keystatsyahooquery',
            options={'get_latest_by': ['-date'], 'ordering': ['-date'], 'verbose_name': 'Yahooquery Key stats', 'verbose_name_plural': 'Yahooquery Key stats'},
        ),
        migrations.AlterModelOptions(
            name='liquidityratio',
            options={'get_latest_by': ['-date', 'period'], 'ordering': ['-date', 'period'], 'verbose_name': 'Liquidity Ratio', 'verbose_name_plural': 'Liquidity Ratios'},
        ),
        migrations.AlterModelOptions(
            name='marginratio',
            options={'get_latest_by': ['-date', 'period'], 'ordering': ['-date', 'period'], 'verbose_name': 'Margin Ratio', 'verbose_name_plural': 'Margin Ratios'},
        ),
        migrations.AlterModelOptions(
            name='nongaap',
            options={'get_latest_by': ['-date', 'period'], 'ordering': ['-date', 'period'], 'verbose_name': 'Non GAAP figure', 'verbose_name_plural': 'Non GAAP figures'},
        ),
        migrations.AlterModelOptions(
            name='operationriskratio',
            options={'get_latest_by': ['-date', 'period'], 'ordering': ['-date', 'period'], 'verbose_name': 'Operation Risk Ratio', 'verbose_name_plural': 'Operation Risk Ratios'},
        ),
        migrations.AlterModelOptions(
            name='persharevalue',
            options={'get_latest_by': ['-date', 'period'], 'ordering': ['-date', 'period'], 'verbose_name': 'Per share', 'verbose_name_plural': 'Per shares'},
        ),
        migrations.AlterModelOptions(
            name='pricetoratio',
            options={'get_latest_by': ['-date', 'period'], 'ordering': ['-date', 'period'], 'verbose_name': 'Price to Ratio', 'verbose_name_plural': 'Price to Ratios'},
        ),
        migrations.AlterModelOptions(
            name='rentabilityratio',
            options={'get_latest_by': ['-date', 'period'], 'ordering': ['-date', 'period'], 'verbose_name': 'Rentability Ratio', 'verbose_name_plural': 'Rentability Ratios'},
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='from_average',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='is_ttm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='accounts_payable',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='cash',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='common_stock',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='deferred_long_term_asset_charges',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='gains_losses_not_affecting_retained_earnings',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='good_will',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='intangible_assets',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='inventory',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='long_term_debt',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='long_term_investments',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='net_receivables',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='net_tangible_assets',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='other_assets',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='other_current_assets',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='other_current_liab',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='other_liab',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='other_stockholder_equity',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='property_plant_equipment',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='retained_earnings',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='short_long_term_debt',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='short_term_investments',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='total_assets',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='total_current_assets',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='total_current_liabilities',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='total_liab',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='total_stockholder_equity',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatement',
            name='from_average',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cashflowstatement',
            name='is_ttm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cashflowstatementyfinance',
            name='capital_expenditures',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyfinance',
            name='change_in_cash',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyfinance',
            name='change_to_account_receivables',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyfinance',
            name='change_to_inventory',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyfinance',
            name='change_to_liabilities',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyfinance',
            name='change_to_netincome',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyfinance',
            name='change_to_operating_activities',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyfinance',
            name='depreciation',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyfinance',
            name='dividends_paid',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyfinance',
            name='effect_of_exchange_rate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyfinance',
            name='investments',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyfinance',
            name='issuance_of_stock',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyfinance',
            name='net_borrowings',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyfinance',
            name='net_income',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyfinance',
            name='other_cashflows_from_financing_activities',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyfinance',
            name='other_cashflows_from_investing_activities',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyfinance',
            name='repurchase_of_stock',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyfinance',
            name='total_cash_from_financing_activities',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyfinance',
            name='total_cash_from_operating_activities',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyfinance',
            name='total_cashflows_from_investing_activities',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='companygrowth',
            name='from_average',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companygrowth',
            name='is_ttm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eficiencyratio',
            name='from_average',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eficiencyratio',
            name='is_ttm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enterprisevalueratio',
            name='from_average',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enterprisevalueratio',
            name='is_ttm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='freecashflowratio',
            name='from_average',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='freecashflowratio',
            name='is_ttm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='from_average',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='is_ttm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incomestatementyfinance',
            name='cost_of_revenue',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyfinance',
            name='discontinued_operations',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyfinance',
            name='ebit',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyfinance',
            name='effect_of_accounting_charges',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyfinance',
            name='extraordinary_items',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyfinance',
            name='gross_profit',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyfinance',
            name='income_before_tax',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyfinance',
            name='income_tax_expense',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyfinance',
            name='interest_expense',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyfinance',
            name='minority_interest',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyfinance',
            name='net_income',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyfinance',
            name='net_income_applicable_to_common_shares',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyfinance',
            name='net_income_from_continuing_ops',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyfinance',
            name='non_recurring',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyfinance',
            name='operating_income',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyfinance',
            name='other_items',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyfinance',
            name='other_operating_expenses',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyfinance',
            name='research_development',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyfinance',
            name='selling_general_administrative',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyfinance',
            name='total_operating_expenses',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyfinance',
            name='total_other_income_expense_net',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyfinance',
            name='total_revenue',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='keystatsyahooquery',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.period'),
        ),
        migrations.AddField(
            model_name='liquidityratio',
            name='from_average',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='liquidityratio',
            name='is_ttm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marginratio',
            name='from_average',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marginratio',
            name='is_ttm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nongaap',
            name='from_average',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nongaap',
            name='is_ttm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operationriskratio',
            name='from_average',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operationriskratio',
            name='is_ttm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='persharevalue',
            name='from_average',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='persharevalue',
            name='is_ttm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pricetoratio',
            name='from_average',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pricetoratio',
            name='is_ttm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentabilityratio',
            name='from_average',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentabilityratio',
            name='is_ttm',
            field=models.BooleanField(default=False),
        ),
    ]
