# Generated by Django 3.2.15 on 2022-09-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0011_auto_20220831_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheet',
            name='is_ttm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cashflowstatement',
            name='is_ttm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companygrowth',
            name='is_ttm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eficiencyratio',
            name='is_ttm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enterprisevalueratio',
            name='is_ttm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='freecashflowratio',
            name='is_ttm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='is_ttm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='liquidityratio',
            name='is_ttm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marginratio',
            name='is_ttm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nongaap',
            name='is_ttm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operationriskratio',
            name='is_ttm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='persharevalue',
            name='is_ttm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pricetoratio',
            name='is_ttm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentabilityratio',
            name='is_ttm',
            field=models.BooleanField(default=False),
        ),
    ]
