# Generated by Django 3.2.15 on 2022-09-29 14:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0011_auto_20220831_2115"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="balancesheet",
            name="is_ttm",
        ),
        migrations.RemoveField(
            model_name="cashflowstatement",
            name="is_ttm",
        ),
        migrations.RemoveField(
            model_name="companygrowth",
            name="is_ttm",
        ),
        migrations.RemoveField(
            model_name="eficiencyratio",
            name="is_ttm",
        ),
        migrations.RemoveField(
            model_name="enterprisevalueratio",
            name="is_ttm",
        ),
        migrations.RemoveField(
            model_name="freecashflowratio",
            name="is_ttm",
        ),
        migrations.RemoveField(
            model_name="incomestatement",
            name="is_ttm",
        ),
        migrations.RemoveField(
            model_name="liquidityratio",
            name="is_ttm",
        ),
        migrations.RemoveField(
            model_name="marginratio",
            name="is_ttm",
        ),
        migrations.RemoveField(
            model_name="nongaap",
            name="is_ttm",
        ),
        migrations.RemoveField(
            model_name="operationriskratio",
            name="is_ttm",
        ),
        migrations.RemoveField(
            model_name="persharevalue",
            name="is_ttm",
        ),
        migrations.RemoveField(
            model_name="pricetoratio",
            name="is_ttm",
        ),
        migrations.RemoveField(
            model_name="rentabilityratio",
            name="is_ttm",
        ),
    ]
