# Generated by Django 3.2.15 on 2022-09-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0013_auto_20220929_1648"),
    ]

    operations = [
        migrations.AddField(
            model_name="balancesheet",
            name="from_average",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cashflowstatement",
            name="from_average",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="companygrowth",
            name="from_average",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eficiencyratio",
            name="from_average",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="enterprisevalueratio",
            name="from_average",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="freecashflowratio",
            name="from_average",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incomestatement",
            name="from_average",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name="keystatsyahooquery",
            table="assets_companies_key_stats_yahooquery",
        ),
    ]
