# Generated by Django 3.2.15 on 2022-09-29 14:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0014_auto_20220925_0923"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="balancesheet",
            options={
                "base_manager_name": "objects",
                "get_latest_by": ["-date", "period"],
                "ordering": ["-date", "period"],
                "verbose_name": "Balance Sheet",
                "verbose_name_plural": "Balance Sheets",
            },
        ),
        migrations.AlterModelOptions(
            name="balancesheetfinprep",
            options={
                "base_manager_name": "objects",
                "get_latest_by": ["-date", "period"],
                "ordering": ["-date", "period"],
                "verbose_name": "Finprep Balance Sheet",
                "verbose_name_plural": "Finprep Balance Sheets",
            },
        ),
        migrations.AlterModelOptions(
            name="balancesheetyahooquery",
            options={
                "base_manager_name": "objects",
                "get_latest_by": ["-date", "period"],
                "ordering": ["-date", "period"],
                "verbose_name": "Yahooquery Balance Sheet",
                "verbose_name_plural": "Yahooquery Balance Sheets",
            },
        ),
        migrations.AlterModelOptions(
            name="balancesheetyfinance",
            options={
                "base_manager_name": "objects",
                "get_latest_by": ["-date", "period"],
                "ordering": ["-date", "period"],
                "verbose_name": "YFinance Balance Sheet",
                "verbose_name_plural": "YFinance Balance Sheets",
            },
        ),
        migrations.AlterModelOptions(
            name="cashflowstatement",
            options={
                "base_manager_name": "objects",
                "get_latest_by": ["-date", "period"],
                "ordering": ["-date", "period"],
                "verbose_name": "Cash flow Statement",
                "verbose_name_plural": "Cash flow Statements",
            },
        ),
        migrations.AlterModelOptions(
            name="cashflowstatementfinprep",
            options={
                "base_manager_name": "objects",
                "get_latest_by": ["-date", "period"],
                "ordering": ["-date", "period"],
                "verbose_name": "Finprep Cash flow Statement",
                "verbose_name_plural": "Finprep Cash flow Statements",
            },
        ),
        migrations.AlterModelOptions(
            name="cashflowstatementyahooquery",
            options={
                "base_manager_name": "objects",
                "get_latest_by": ["-date", "period"],
                "ordering": ["-date", "period"],
                "verbose_name": "Yahooquery Cash flow Statement",
                "verbose_name_plural": "Yahooquery Cash flow Statements",
            },
        ),
        migrations.AlterModelOptions(
            name="cashflowstatementyfinance",
            options={
                "base_manager_name": "objects",
                "get_latest_by": ["-date", "period"],
                "ordering": ["-date", "period"],
                "verbose_name": "YFinance Cash flow Statement",
                "verbose_name_plural": "YFinance Cash flow Statements",
            },
        ),
        migrations.AlterModelOptions(
            name="companygrowth",
            options={
                "base_manager_name": "objects",
                "get_latest_by": ["-date", "period"],
                "ordering": ["-date", "period"],
                "verbose_name": "Company growth",
                "verbose_name_plural": "Companies growth",
            },
        ),
        migrations.AlterModelOptions(
            name="eficiencyratio",
            options={
                "base_manager_name": "objects",
                "get_latest_by": ["-date", "period"],
                "ordering": ["-date", "period"],
                "verbose_name": "Efficiency Ratio",
                "verbose_name_plural": "Efficiency Ratios",
            },
        ),
        migrations.AlterModelOptions(
            name="enterprisevalueratio",
            options={
                "base_manager_name": "objects",
                "get_latest_by": ["-date", "period"],
                "ordering": ["-date", "period"],
                "verbose_name": "Enterprise Value",
                "verbose_name_plural": "Enterprise Values",
            },
        ),
        migrations.AlterModelOptions(
            name="freecashflowratio",
            options={
                "base_manager_name": "objects",
                "get_latest_by": ["-date", "period"],
                "ordering": ["-date", "period"],
                "verbose_name": "Free cash flow Ratio",
                "verbose_name_plural": "Free cash flow Ratios",
            },
        ),
        migrations.AlterModelOptions(
            name="incomestatement",
            options={
                "base_manager_name": "objects",
                "get_latest_by": ["-date", "period"],
                "ordering": ["-date", "period"],
                "verbose_name": "Income Statement",
                "verbose_name_plural": "Income Statements",
            },
        ),
        migrations.AlterModelOptions(
            name="incomestatementfinprep",
            options={
                "base_manager_name": "objects",
                "get_latest_by": ["-date", "period"],
                "ordering": ["-date", "period"],
                "verbose_name": "Finprep Income Statement",
                "verbose_name_plural": "Finprep Income Statements",
            },
        ),
        migrations.AlterModelOptions(
            name="incomestatementyahooquery",
            options={
                "base_manager_name": "objects",
                "get_latest_by": ["-date", "period"],
                "ordering": ["-date", "period"],
                "verbose_name": "Yahooquery Income Statement",
                "verbose_name_plural": "Yahooquery Income Statements",
            },
        ),
        migrations.AlterModelOptions(
            name="incomestatementyfinance",
            options={
                "base_manager_name": "objects",
                "get_latest_by": ["-date", "period"],
                "ordering": ["-date", "period"],
                "verbose_name": "YFinance Income Statement",
                "verbose_name_plural": "YFinance Income Statements",
            },
        ),
        migrations.AlterModelOptions(
            name="keystatsyahooquery",
            options={
                "base_manager_name": "objects",
                "get_latest_by": ["-date"],
                "ordering": ["-date"],
                "verbose_name": "Yahooquery Key stats",
                "verbose_name_plural": "Yahooquery Key stats",
            },
        ),
        migrations.AlterModelOptions(
            name="liquidityratio",
            options={
                "base_manager_name": "objects",
                "get_latest_by": ["-date", "period"],
                "ordering": ["-date", "period"],
                "verbose_name": "Liquidity Ratio",
                "verbose_name_plural": "Liquidity Ratios",
            },
        ),
        migrations.AlterModelOptions(
            name="marginratio",
            options={
                "base_manager_name": "objects",
                "get_latest_by": ["-date", "period"],
                "ordering": ["-date", "period"],
                "verbose_name": "Margin Ratio",
                "verbose_name_plural": "Margin Ratios",
            },
        ),
        migrations.AlterModelOptions(
            name="nongaap",
            options={
                "base_manager_name": "objects",
                "get_latest_by": ["-date", "period"],
                "ordering": ["-date", "period"],
                "verbose_name": "Non GAAP figure",
                "verbose_name_plural": "Non GAAP figures",
            },
        ),
        migrations.AlterModelOptions(
            name="operationriskratio",
            options={
                "base_manager_name": "objects",
                "get_latest_by": ["-date", "period"],
                "ordering": ["-date", "period"],
                "verbose_name": "Operation Risk Ratio",
                "verbose_name_plural": "Operation Risk Ratios",
            },
        ),
        migrations.AlterModelOptions(
            name="persharevalue",
            options={
                "base_manager_name": "objects",
                "get_latest_by": ["-date", "period"],
                "ordering": ["-date", "period"],
                "verbose_name": "Per share",
                "verbose_name_plural": "Per shares",
            },
        ),
        migrations.AlterModelOptions(
            name="pricetoratio",
            options={
                "base_manager_name": "objects",
                "get_latest_by": ["-date", "period"],
                "ordering": ["-date", "period"],
                "verbose_name": "Price to Ratio",
                "verbose_name_plural": "Price to Ratios",
            },
        ),
        migrations.AlterModelOptions(
            name="rentabilityratio",
            options={
                "base_manager_name": "objects",
                "get_latest_by": ["-date", "period"],
                "ordering": ["-date", "period"],
                "verbose_name": "Rentability Ratio",
                "verbose_name_plural": "Rentability Ratios",
            },
        ),
    ]
