# Generated by Django 3.2.15 on 2022-09-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0013_auto_20220907_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='accounts_payable',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='cash',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='common_stock',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='deferred_long_term_asset_charges',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='gains_losses_not_affecting_retained_earnings',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='good_will',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='intangible_assets',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='inventory',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='long_term_debt',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='long_term_investments',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='net_receivables',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='net_tangible_assets',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='other_assets',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='other_current_assets',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='other_current_liab',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='other_liab',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='other_stockholder_equity',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='property_plant_equipment',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='retained_earnings',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='short_long_term_debt',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='short_term_investments',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='total_assets',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='total_current_assets',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='total_current_liabilities',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='total_liab',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='balancesheetyfinance',
            name='total_stockholder_equity',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyfinance',
            name='capital_expenditures',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyfinance',
            name='change_in_cash',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyfinance',
            name='change_to_account_receivables',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyfinance',
            name='change_to_inventory',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyfinance',
            name='change_to_liabilities',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyfinance',
            name='change_to_netincome',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyfinance',
            name='change_to_operating_activities',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyfinance',
            name='depreciation',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyfinance',
            name='dividends_paid',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyfinance',
            name='effect_of_exchange_rate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyfinance',
            name='investments',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyfinance',
            name='issuance_of_stock',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyfinance',
            name='net_borrowings',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyfinance',
            name='net_income',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyfinance',
            name='other_cashflows_from_financing_activities',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyfinance',
            name='other_cashflows_from_investing_activities',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyfinance',
            name='repurchase_of_stock',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyfinance',
            name='total_cash_from_financing_activities',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyfinance',
            name='total_cash_from_operating_activities',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatementyfinance',
            name='total_cashflows_from_investing_activities',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyfinance',
            name='cost_of_revenue',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyfinance',
            name='discontinued_operations',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyfinance',
            name='ebit',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyfinance',
            name='effect_of_accounting_charges',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyfinance',
            name='extraordinary_items',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyfinance',
            name='gross_profit',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyfinance',
            name='income_before_tax',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyfinance',
            name='income_tax_expense',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyfinance',
            name='interest_expense',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyfinance',
            name='minority_interest',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyfinance',
            name='net_income',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyfinance',
            name='net_income_applicable_to_common_shares',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyfinance',
            name='net_income_from_continuing_ops',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyfinance',
            name='non_recurring',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyfinance',
            name='operating_income',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyfinance',
            name='other_items',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyfinance',
            name='other_operating_expenses',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyfinance',
            name='research_development',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyfinance',
            name='selling_general_administrative',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyfinance',
            name='total_operating_expenses',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyfinance',
            name='total_other_income_expense_net',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomestatementyfinance',
            name='total_revenue',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
