# Generated by Django 3.2.15 on 2022-11-25 21:59

import src.general.mixins
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("classifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Roadmap",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=800)),
                ("slug", models.SlugField(blank=True, max_length=800)),
                ("content", ckeditor.fields.RichTextField()),
                ("total_votes", models.IntegerField(default=0)),
                ("total_views", models.PositiveBigIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("finished", "Finished"),
                            ("pending", "Pending"),
                            ("doing", "Doing"),
                            ("testing", "Testing"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "downvotes",
                    models.ManyToManyField(
                        blank=True, related_name="user_downvote_roadmap", to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="classifications.Tag")),
                (
                    "upvotes",
                    models.ManyToManyField(blank=True, related_name="user_upvote_roadmap", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "Roadmap",
                "db_table": "website_roadmap",
            },
            bases=(
                models.Model,
                src.general.mixins.BaseToAllMixin,
                src.general.mixins.CommentsMixin,
                src.general.mixins.VotesMixin,
            ),
        ),
        migrations.CreateModel(
            name="RoadmapComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField()),
                (
                    "author",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "content_related",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments_related",
                        to="web.roadmap",
                    ),
                ),
            ],
            options={
                "verbose_name": "Roadmap's comment",
                "db_table": "website_roadmap_comments",
            },
            bases=(models.Model, src.general.mixins.BaseToAllMixin),
        ),
    ]
