# Generated by Django 3.2.15 on 2022-11-30 19:32

import src.escritos.abstracts
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("classifications", "0001_initial"),
        ("web", "0003_auto_20221128_2315"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadmap",
            name="category",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="classifications.category"
            ),
        ),
        migrations.AddField(
            model_name="roadmap",
            name="checkings",
            field=models.JSONField(default=src.escritos.abstracts.default_dict),
        ),
        migrations.AddField(
            model_name="roadmap",
            name="times_shared",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="roadmap",
            name="slug",
            field=models.SlugField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name="roadmap",
            name="title",
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name="roadmap",
            name="total_views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
