# Generated by Django 3.2.16 on 2022-12-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_websiteemail_call_to_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteemail',
            name='call_to_action_url',
            field=models.SlugField(default='', max_length=500),
        ),
    ]
