# Generated by Django 3.2.15 on 2022-10-27 07:03

import apps.general.mixins
import apps.users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notifications',
            field=models.JSONField(default=apps.users.models.default_dict),
        ),
        migrations.CreateModel(
            name='UsersCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=800)),
                ('slug', models.SlugField(blank=True, max_length=800, null=True)),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Users category',
                'db_table': 'users_categories',
                'ordering': ['-id'],
            },
            bases=(models.Model, apps.general.mixins.BaseToAllMixin),
        ),
    ]
