# Generated by Django 3.2.15 on 2022-08-28 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(blank=True, max_length=50, null=True)),
                ('country_code', models.CharField(blank=True, max_length=10000, null=True)),
                ('country_name', models.CharField(blank=True, max_length=10000, null=True)),
                ('dma_code', models.CharField(blank=True, max_length=10000, null=True)),
                ('is_in_european_union', models.BooleanField(default=False)),
                ('latitude', models.CharField(blank=True, max_length=10000, null=True)),
                ('longitude', models.CharField(blank=True, max_length=10000, null=True)),
                ('city', models.CharField(blank=True, max_length=10000, null=True)),
                ('region', models.CharField(blank=True, max_length=10000, null=True)),
                ('time_zone', models.CharField(blank=True, max_length=10000, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10000, null=True)),
                ('continent_code', models.CharField(blank=True, max_length=10000, null=True)),
                ('continent_name', models.CharField(blank=True, max_length=10000, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=10000, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meta_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta profile info',
                'db_table': 'user_meta_profile_information',
            },
        ),
    ]
