# Generated by Django 3.2.15 on 2022-10-13 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedias', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogsharedhistorial',
            name='inside_information',
        ),
        migrations.RemoveField(
            model_name='companysharedhistorial',
            name='inside_information',
        ),
        migrations.RemoveField(
            model_name='newssharedhistorial',
            name='inside_information',
        ),
        migrations.RemoveField(
            model_name='profilesharedhistorial',
            name='inside_information',
        ),
        migrations.RemoveField(
            model_name='questionsharedhistorial',
            name='inside_information',
        ),
        migrations.RemoveField(
            model_name='termsharedhistorial',
            name='inside_information',
        ),
        migrations.AddField(
            model_name='blogsharedhistorial',
            name='default_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='socialmedias.defaultcontent'),
        ),
        migrations.AddField(
            model_name='blogsharedhistorial',
            name='default_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='socialmedias.defaulttilte'),
        ),
        migrations.AddField(
            model_name='blogsharedhistorial',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='blogsharedhistorial',
            name='title_emojis',
            field=models.ManyToManyField(blank=True, to='socialmedias.Emoji'),
        ),
        migrations.AddField(
            model_name='companysharedhistorial',
            name='default_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='socialmedias.defaultcontent'),
        ),
        migrations.AddField(
            model_name='companysharedhistorial',
            name='default_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='socialmedias.defaulttilte'),
        ),
        migrations.AddField(
            model_name='companysharedhistorial',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='companysharedhistorial',
            name='title_emojis',
            field=models.ManyToManyField(blank=True, to='socialmedias.Emoji'),
        ),
        migrations.AddField(
            model_name='newssharedhistorial',
            name='default_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='socialmedias.defaultcontent'),
        ),
        migrations.AddField(
            model_name='newssharedhistorial',
            name='default_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='socialmedias.defaulttilte'),
        ),
        migrations.AddField(
            model_name='newssharedhistorial',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='newssharedhistorial',
            name='title_emojis',
            field=models.ManyToManyField(blank=True, to='socialmedias.Emoji'),
        ),
        migrations.AddField(
            model_name='profilesharedhistorial',
            name='default_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='socialmedias.defaultcontent'),
        ),
        migrations.AddField(
            model_name='profilesharedhistorial',
            name='default_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='socialmedias.defaulttilte'),
        ),
        migrations.AddField(
            model_name='profilesharedhistorial',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='profilesharedhistorial',
            name='title_emojis',
            field=models.ManyToManyField(blank=True, to='socialmedias.Emoji'),
        ),
        migrations.AddField(
            model_name='questionsharedhistorial',
            name='default_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='socialmedias.defaultcontent'),
        ),
        migrations.AddField(
            model_name='questionsharedhistorial',
            name='default_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='socialmedias.defaulttilte'),
        ),
        migrations.AddField(
            model_name='questionsharedhistorial',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='questionsharedhistorial',
            name='title_emojis',
            field=models.ManyToManyField(blank=True, to='socialmedias.Emoji'),
        ),
        migrations.AddField(
            model_name='termsharedhistorial',
            name='default_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='socialmedias.defaultcontent'),
        ),
        migrations.AddField(
            model_name='termsharedhistorial',
            name='default_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='socialmedias.defaulttilte'),
        ),
        migrations.AddField(
            model_name='termsharedhistorial',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='termsharedhistorial',
            name='title_emojis',
            field=models.ManyToManyField(blank=True, to='socialmedias.Emoji'),
        ),
    ]
