# Generated by Django 3.2.14 on 2022-07-28 19:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedias', '0003_auto_20220515_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('for_content', models.PositiveIntegerField(blank=True, choices=[(0, 'All'), (1, 'Question'), (2, 'News'), (3, 'Term'), (4, 'Blog'), (5, 'Company'), (6, 'Web')], default=0)),
                ('purpose', models.CharField(blank=True, choices=[('promotion', 'Promotion'), ('suggestion', 'Suggestion'), ('announcement', 'Announcement'), ('welcome', 'Welcome'), ('engagement', 'Engagement')], max_length=500, null=True)),
                ('content', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Default content',
                'db_table': 'socialmedia_content',
            },
        ),
        migrations.RenameField(
            model_name='hashtag',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='defaulttilte',
            name='for_model',
        ),
        migrations.AddField(
            model_name='defaulttilte',
            name='for_content',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'All'), (1, 'Question'), (2, 'News'), (3, 'Term'), (4, 'Blog'), (5, 'Company'), (6, 'Web')], default=0),
        ),
        migrations.AddField(
            model_name='defaulttilte',
            name='purpose',
            field=models.CharField(blank=True, choices=[('promotion', 'Promotion'), ('suggestion', 'Suggestion'), ('announcement', 'Announcement'), ('welcome', 'Welcome'), ('engagement', 'Engagement')], max_length=500, null=True),
        ),
    ]
