# Generated by Django 3.2.15 on 2022-10-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedias', '0003_auto_20221013_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogsharedhistorial',
            old_name='description',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='companysharedhistorial',
            old_name='description',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='newssharedhistorial',
            old_name='description',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='profilesharedhistorial',
            old_name='description',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='questionsharedhistorial',
            old_name='description',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='termsharedhistorial',
            old_name='description',
            new_name='content',
        ),
        migrations.AddField(
            model_name='blogsharedhistorial',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='socialmedias.Hashtag'),
        ),
        migrations.AddField(
            model_name='companysharedhistorial',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='socialmedias.Hashtag'),
        ),
        migrations.AddField(
            model_name='newssharedhistorial',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='socialmedias.Hashtag'),
        ),
        migrations.AddField(
            model_name='profilesharedhistorial',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='socialmedias.Hashtag'),
        ),
        migrations.AddField(
            model_name='questionsharedhistorial',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='socialmedias.Hashtag'),
        ),
        migrations.AddField(
            model_name='termsharedhistorial',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='socialmedias.Hashtag'),
        ),
        migrations.AlterField(
            model_name='defaultcontent',
            name='for_content',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'All'), (1, 'Question'), (2, 'News'), (3, 'Term'), (4, 'PublicBlog'), (5, 'Company'), (6, 'Web')], default=0),
        ),
        migrations.AlterField(
            model_name='defaulttilte',
            name='for_content',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'All'), (1, 'Question'), (2, 'News'), (3, 'Term'), (4, 'PublicBlog'), (5, 'Company'), (6, 'Web')], default=0),
        ),
    ]
