# Generated by Django 3.2.15 on 2022-10-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedias', '0004_auto_20221016_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultcontent',
            name='purpose',
            field=models.CharField(blank=True, choices=[('promotion', 'Promotion'), ('suggestion', 'Suggestion'), ('announcement', 'Announcement'), ('welcome', 'Welcome'), ('engagement', 'Engagement'), ('engagement-user-no-active', 'Engagement user no active'), ('engagement-user-little-active', 'Engagement user little active'), ('engagement-user-first-call', 'Engagement user first call'), ('newsletter', 'Newsletter'), ('newsletter-blog', 'Newsletter for blog'), ('newsletter-public-blog', 'Newsletter  for public blog'), ('newsletter-term', 'Newsletter for term'), ('newsletter-company', 'Newsletter for company'), ('newsletter-company-news', 'Newsletter for company news'), ('newsletter-company-report', 'Newsletter for company report')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='defaulttilte',
            name='purpose',
            field=models.CharField(blank=True, choices=[('promotion', 'Promotion'), ('suggestion', 'Suggestion'), ('announcement', 'Announcement'), ('welcome', 'Welcome'), ('engagement', 'Engagement'), ('engagement-user-no-active', 'Engagement user no active'), ('engagement-user-little-active', 'Engagement user little active'), ('engagement-user-first-call', 'Engagement user first call'), ('newsletter', 'Newsletter'), ('newsletter-blog', 'Newsletter for blog'), ('newsletter-public-blog', 'Newsletter  for public blog'), ('newsletter-term', 'Newsletter for term'), ('newsletter-company', 'Newsletter for company'), ('newsletter-company-news', 'Newsletter for company news'), ('newsletter-company-report', 'Newsletter for company report')], max_length=500, null=True),
        ),
    ]
