# Generated by Django 3.2.14 on 2022-08-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedias', '0004_auto_20220728_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultcontent',
            name='purpose',
            field=models.CharField(blank=True, choices=[('promotion', 'Promotion'), ('suggestion', 'Suggestion'), ('announcement', 'Announcement'), ('welcome', 'Welcome'), ('engagement', 'Engagement'), ('engagement-user-no-active', 'Engagement user no active'), ('engagement-user-little-active', 'Engagement user little active')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='defaulttilte',
            name='purpose',
            field=models.CharField(blank=True, choices=[('promotion', 'Promotion'), ('suggestion', 'Suggestion'), ('announcement', 'Announcement'), ('welcome', 'Welcome'), ('engagement', 'Engagement'), ('engagement-user-no-active', 'Engagement user no active'), ('engagement-user-little-active', 'Engagement user little active')], max_length=500, null=True),
        ),
    ]
