# Generated by Django 3.2.15 on 2022-08-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedias', '0005_auto_20220801_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsharedhistorial',
            name='platform_shared',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('reddit', 'Reddit'), ('whatsapp', 'Whatsapp'), ('linkedin', 'Linkedin'), ('pinterest', 'Pinterest'), ('tumblr', 'Tumblr'), ('youtube', 'Youtube'), ('instagram', 'Instagram')], max_length=500),
        ),
        migrations.AlterField(
            model_name='companysharedhistorial',
            name='platform_shared',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('reddit', 'Reddit'), ('whatsapp', 'Whatsapp'), ('linkedin', 'Linkedin'), ('pinterest', 'Pinterest'), ('tumblr', 'Tumblr'), ('youtube', 'Youtube'), ('instagram', 'Instagram')], max_length=500),
        ),
        migrations.AlterField(
            model_name='defaultcontent',
            name='purpose',
            field=models.CharField(blank=True, choices=[('promotion', 'Promotion'), ('suggestion', 'Suggestion'), ('announcement', 'Announcement'), ('welcome', 'Welcome'), ('engagement', 'Engagement'), ('engagement-user-no-active', 'Engagement user no active'), ('engagement-user-little-active', 'Engagement user little active'), ('engagement-user-first-call', 'Engagement user first call')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='defaulttilte',
            name='purpose',
            field=models.CharField(blank=True, choices=[('promotion', 'Promotion'), ('suggestion', 'Suggestion'), ('announcement', 'Announcement'), ('welcome', 'Welcome'), ('engagement', 'Engagement'), ('engagement-user-no-active', 'Engagement user no active'), ('engagement-user-little-active', 'Engagement user little active'), ('engagement-user-first-call', 'Engagement user first call')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('reddit', 'Reddit'), ('whatsapp', 'Whatsapp'), ('linkedin', 'Linkedin'), ('pinterest', 'Pinterest'), ('tumblr', 'Tumblr'), ('youtube', 'Youtube'), ('instagram', 'Instagram')], max_length=500),
        ),
        migrations.AlterField(
            model_name='newssharedhistorial',
            name='platform_shared',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('reddit', 'Reddit'), ('whatsapp', 'Whatsapp'), ('linkedin', 'Linkedin'), ('pinterest', 'Pinterest'), ('tumblr', 'Tumblr'), ('youtube', 'Youtube'), ('instagram', 'Instagram')], max_length=500),
        ),
        migrations.AlterField(
            model_name='profilesharedhistorial',
            name='platform_shared',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('reddit', 'Reddit'), ('whatsapp', 'Whatsapp'), ('linkedin', 'Linkedin'), ('pinterest', 'Pinterest'), ('tumblr', 'Tumblr'), ('youtube', 'Youtube'), ('instagram', 'Instagram')], max_length=500),
        ),
        migrations.AlterField(
            model_name='questionsharedhistorial',
            name='platform_shared',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('reddit', 'Reddit'), ('whatsapp', 'Whatsapp'), ('linkedin', 'Linkedin'), ('pinterest', 'Pinterest'), ('tumblr', 'Tumblr'), ('youtube', 'Youtube'), ('instagram', 'Instagram')], max_length=500),
        ),
        migrations.AlterField(
            model_name='termsharedhistorial',
            name='platform_shared',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('reddit', 'Reddit'), ('whatsapp', 'Whatsapp'), ('linkedin', 'Linkedin'), ('pinterest', 'Pinterest'), ('tumblr', 'Tumblr'), ('youtube', 'Youtube'), ('instagram', 'Instagram')], max_length=500),
        ),
    ]
