# Generated by Django 3.2.15 on 2022-09-19 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visiteur',
            old_name='HTTP_USER_AGENT',
            new_name='http_user_agent',
        ),
    ]
