# Generated by Django 3.2.14 on 2022-07-27 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seo', '0012_auto_20220725_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjourney',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visiteurjourney',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='seo.visiteur'),
        ),
    ]
