# Generated by Django 3.2.16 on 2023-05-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedias', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaauth',
            name='page_id',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='socialmediaauth',
            name='page_name',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediaauth',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
