# Generated by Django 3.2.16 on 2022-12-18 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import src.general.mixins


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialmedias', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsharedhistorial',
            name='platform_shared',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('reddit', 'Reddit'), ('whatsapp', 'Whatsapp'), ('linkedin', 'Linkedin'), ('pinterest', 'Pinterest'), ('tumblr', 'Tumblr'), ('youtube', 'Youtube'), ('instagram', 'Instagram')], max_length=12),
        ),
        migrations.AlterField(
            model_name='companysharedhistorial',
            name='platform_shared',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('reddit', 'Reddit'), ('whatsapp', 'Whatsapp'), ('linkedin', 'Linkedin'), ('pinterest', 'Pinterest'), ('tumblr', 'Tumblr'), ('youtube', 'Youtube'), ('instagram', 'Instagram')], max_length=12),
        ),
        migrations.AlterField(
            model_name='newssharedhistorial',
            name='platform_shared',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('reddit', 'Reddit'), ('whatsapp', 'Whatsapp'), ('linkedin', 'Linkedin'), ('pinterest', 'Pinterest'), ('tumblr', 'Tumblr'), ('youtube', 'Youtube'), ('instagram', 'Instagram')], max_length=12),
        ),
        migrations.AlterField(
            model_name='profilesharedhistorial',
            name='platform_shared',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('reddit', 'Reddit'), ('whatsapp', 'Whatsapp'), ('linkedin', 'Linkedin'), ('pinterest', 'Pinterest'), ('tumblr', 'Tumblr'), ('youtube', 'Youtube'), ('instagram', 'Instagram')], max_length=12),
        ),
        migrations.AlterField(
            model_name='questionsharedhistorial',
            name='platform_shared',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('reddit', 'Reddit'), ('whatsapp', 'Whatsapp'), ('linkedin', 'Linkedin'), ('pinterest', 'Pinterest'), ('tumblr', 'Tumblr'), ('youtube', 'Youtube'), ('instagram', 'Instagram')], max_length=12),
        ),
        migrations.AlterField(
            model_name='termsharedhistorial',
            name='platform_shared',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('reddit', 'Reddit'), ('whatsapp', 'Whatsapp'), ('linkedin', 'Linkedin'), ('pinterest', 'Pinterest'), ('tumblr', 'Tumblr'), ('youtube', 'Youtube'), ('instagram', 'Instagram')], max_length=12),
        ),
        migrations.CreateModel(
            name='SocialmediaAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('socialmedia', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('reddit', 'Reddit'), ('whatsapp', 'Whatsapp'), ('linkedin', 'Linkedin'), ('pinterest', 'Pinterest'), ('tumblr', 'Tumblr'), ('youtube', 'Youtube'), ('instagram', 'Instagram')], max_length=12)),
                ('metadata', models.JSONField(default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Socialmedia authentication',
                'db_table': 'socialmedia_auth',
            },
            bases=(models.Model, src.general.mixins.BaseToAllMixin),
        ),
    ]
