# Generated by Django 3.2.16 on 2022-12-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedias', '0003_auto_20221218_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaauth',
            name='title',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
