# Generated by Django 3.2.16 on 2022-12-26 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("public_blog", "0007_auto_20221226_1548"),
        ("socialmedias", "0004_socialmediaauth_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilesharedhistorial",
            name="content_shared",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profiles_shared",
                to="public_blog.writerprofile",
            ),
        ),
    ]
