# Generated by Django 3.2.15 on 2022-12-05 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balancesheet',
            old_name='account_payables',
            new_name='accounts_payable',
        ),
        migrations.RenameField(
            model_name='cashflowstatement',
            old_name='accounts_receivables',
            new_name='accounts_receivable',
        ),
        migrations.RenameField(
            model_name='cashflowstatement',
            old_name='stock_based_compesation',
            new_name='stock_based_compensation',
        ),
    ]
