# Generated by Django 4.2.7 on 2023-11-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0002_auto_20230529_1209"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchange",
            name="exchange",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="exchange",
            name="exchange_ticker",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="exchangeorganisation",
            name="image",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="exchangeorganisation",
            name="name",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="exchangeorganisation",
            name="sub_exchange1",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="exchangeorganisation",
            name="sub_exchange2",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
    ]
