# Generated by Django 3.2.15 on 2022-12-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_auto_20221212_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheet',
            name='preferred_stocks',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
