# Generated by Django 4.2.7 on 2023-11-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0003_alter_exchange_exchange_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="need_parsing",
            field=models.BooleanField(default=False),
        ),
    ]
