# Generated by Django 3.2.15 on 2022-09-29 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preguntas_respuestas', '0001_initial'),
        ('seo', '0001_initial'),
        ('public_blog', '0001_initial'),
        ('recsys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visiteurtermrecommended',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seo.visiteur'),
        ),
        migrations.AddField(
            model_name='visiteurquestionrecommended',
            name='model_recommended',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='preguntas_respuestas.question'),
        ),
        migrations.AddField(
            model_name='visiteurquestionrecommended',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seo.visiteur'),
        ),
        migrations.AddField(
            model_name='visiteurpublicblogrecommended',
            name='model_recommended',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='public_blog.publicblog'),
        ),
        migrations.AddField(
            model_name='visiteurpublicblogrecommended',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seo.visiteur'),
        ),
    ]
