# Generated by Django 3.2.15 on 2022-10-27 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercompanyrecommended',
            old_name='kind',
            new_name='style',
        ),
        migrations.RenameField(
            model_name='userproductcomplementaryrecommended',
            old_name='kind',
            new_name='style',
        ),
        migrations.RenameField(
            model_name='userpromotionrecommended',
            old_name='kind',
            new_name='style',
        ),
        migrations.RenameField(
            model_name='userpublicblogrecommended',
            old_name='kind',
            new_name='style',
        ),
        migrations.RenameField(
            model_name='userquestionrecommended',
            old_name='kind',
            new_name='style',
        ),
        migrations.RenameField(
            model_name='usertermrecommended',
            old_name='kind',
            new_name='style',
        ),
        migrations.RenameField(
            model_name='visiteurcompanyrecommended',
            old_name='kind',
            new_name='style',
        ),
        migrations.RenameField(
            model_name='visiteurproductcomplementaryrecommended',
            old_name='kind',
            new_name='style',
        ),
        migrations.RenameField(
            model_name='visiteurpromotionrecommended',
            old_name='kind',
            new_name='style',
        ),
        migrations.RenameField(
            model_name='visiteurpublicblogrecommended',
            old_name='kind',
            new_name='style',
        ),
        migrations.RenameField(
            model_name='visiteurquestionrecommended',
            old_name='kind',
            new_name='style',
        ),
        migrations.RenameField(
            model_name='visiteurtermrecommended',
            old_name='kind',
            new_name='style',
        ),
    ]
