# Generated by Django 3.2.15 on 2022-09-29 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seo', '0001_initial'),
        ('socialmedias', '0001_initial'),
        ('public_blog', '0001_initial'),
        ('general', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='writterprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writter_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicblogcomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicblogcomment',
            name='content_related',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_related', to='public_blog.publicblog'),
        ),
        migrations.AddField(
            model_name='publicblogasnewsletter',
            name='blog_related',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_blog_newsletter', to='public_blog.publicblog'),
        ),
        migrations.AddField(
            model_name='publicblogasnewsletter',
            name='default_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='socialmedias.defaultcontent'),
        ),
        migrations.AddField(
            model_name='publicblogasnewsletter',
            name='default_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='socialmedias.defaulttilte'),
        ),
        migrations.AddField(
            model_name='publicblogasnewsletter',
            name='title_emojis',
            field=models.ManyToManyField(blank=True, to='socialmedias.Emoji'),
        ),
        migrations.AddField(
            model_name='publicblog',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicblog',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.category'),
        ),
        migrations.AddField(
            model_name='publicblog',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='user_downvote_blog', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicblog',
            name='meta_information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seo.metaparametershistorial'),
        ),
        migrations.AddField(
            model_name='publicblog',
            name='tags',
            field=models.ManyToManyField(blank=True, to='general.Tag'),
        ),
        migrations.AddField(
            model_name='publicblog',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='user_upvote_blog', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newsletterfollowers',
            name='followers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newsletterfollowers',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_writter_followed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followinghistorial',
            name='user_followed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_followed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followinghistorial',
            name='user_following',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailpublicblog',
            name='email_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_related', to='public_blog.publicblogasnewsletter'),
        ),
        migrations.AddField(
            model_name='emailpublicblog',
            name='sent_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
