# Generated by Django 3.2.15 on 2022-10-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public_blog", "0005_rename_extra_data_publicblog_checkings"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicblogasnewsletter",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="publicblogasnewsletter",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="publicblogcomment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="publicblog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="publicblog",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="publicblogcomment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
