# Generated by Django 3.2.14 on 2022-07-28 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedias', '0004_auto_20220728_2136'),
        ('public_blog', '0006_auto_20220603_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicblogasnewsletter',
            name='default_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='socialmedias.defaultcontent'),
        ),
        migrations.AddField(
            model_name='publicblogasnewsletter',
            name='default_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='socialmedias.defaulttilte'),
        ),
        migrations.AddField(
            model_name='publicblogasnewsletter',
            name='title_emojis',
            field=models.ManyToManyField(blank=True, to='socialmedias.Emoji'),
        ),
    ]
