# Generated by Django 3.2.15 on 2022-11-04 22:43

import src.general.mixins
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, max_length=600)),
                ("slug", models.SlugField(blank=True, max_length=800, null=True)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "focused_on",
                    models.CharField(
                        choices=[
                            ("promotion", "Promotion"),
                            ("suggestion", "Suggestion"),
                            ("announcement", "Announcement"),
                            ("welcome", "Welcome"),
                            ("engagement", "Engagement"),
                            ("newsletter", "Newsletter"),
                        ],
                        max_length=250,
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign",
                "db_table": "campaigns",
            },
            bases=(models.Model, src.general.mixins.BaseToAllMixin),
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, max_length=600)),
                ("content", ckeditor.fields.RichTextField()),
                ("thumbnail", models.CharField(blank=True, max_length=600)),
                ("slug", models.SlugField(blank=True, max_length=800, null=True)),
                ("prize", models.PositiveBigIntegerField(default=0)),
                ("shareable_url", models.SlugField(blank=True, max_length=600)),
                ("redirect_to", models.SlugField(blank=True, max_length=600)),
                (
                    "medium",
                    models.CharField(
                        choices=[
                            ("ads", "Ads"),
                            ("email", "Email"),
                            ("web", "Web"),
                            ("social-media-posts", "Social media posts"),
                        ],
                        default="web",
                        max_length=250,
                    ),
                ),
                (
                    "web_promotion_style",
                    models.CharField(
                        blank=True,
                        choices=[("pop_up", "Pop up"), ("banner", "Big Banner"), ("lista", "List"), ("solo", "Solo")],
                        max_length=250,
                    ),
                ),
                (
                    "web_location",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("all-web", "Toda la web"),
                            ("web-inicio", "Web Inicio"),
                            ("screener-inicio", "Screener Inicio"),
                            ("screener-market", "Screener Market"),
                            ("screener-company", "Screener Company"),
                            ("cartera-inicio", "Cartera Inicio"),
                            ("cartera-financials", "Cartera Financials"),
                            ("cartera-balance", "Cartera Balance"),
                            ("private-profile", "Private Profile"),
                            ("public-profile", "Public Profile"),
                            ("question-inicio", "Question Inicio"),
                            ("question-details", "Question Details"),
                            ("term-inicio", "Term Inicio"),
                            ("term-details", "Term Details"),
                            ("blog-inicio", "Blog Inicio"),
                            ("blog-details", "Blog Details"),
                        ],
                        max_length=250,
                    ),
                ),
                (
                    "web_place",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("side", "Side"),
                            ("top", "Top"),
                            ("middle", "Middle"),
                            ("bottom", "Bottom"),
                            ("in_between", "In between"),
                        ],
                        max_length=250,
                    ),
                ),
                (
                    "social_media",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("facebook", "Facebook"),
                            ("twitter", "Twitter"),
                            ("reddit", "Reddit"),
                            ("whatsapp", "Whatsapp"),
                            ("linkedin", "Linkedin"),
                            ("pinterest", "Pinterest"),
                            ("tumblr", "Tumblr"),
                            ("youtube", "Youtube"),
                            ("instagram", "Instagram"),
                        ],
                        max_length=250,
                    ),
                ),
                ("publication_date", models.DateTimeField(blank=True)),
                ("reuse", models.BooleanField(default=False)),
                ("times_to_reuse", models.PositiveBigIntegerField(default=0)),
                ("clicks_by_user", models.PositiveBigIntegerField(default=0)),
                ("clicks_by_not_user", models.PositiveBigIntegerField(default=0)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promotions",
                        to="promotions.campaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Promotion",
                "db_table": "promotions",
            },
            bases=(models.Model, src.general.mixins.BaseToAllMixin),
        ),
    ]
