# Generated by Django 3.2.15 on 2022-12-31 14:33

import ckeditor.fields
from django.db import migrations, models
import src.escritos.abstracts
import src.general.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('is_accepted', models.BooleanField(default=False)),
                ('total_votes', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Answer',
                'db_table': 'answers',
                'ordering': ['-id'],
            },
            bases=(models.Model, src.general.mixins.BaseToAllMixin, src.general.mixins.CommentsMixin, src.general.mixins.VotesMixin),
        ),
        migrations.CreateModel(
            name='AnswerComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': "Answer's comment",
                'db_table': 'answer_comments',
            },
            bases=(models.Model, src.general.mixins.BaseToAllMixin),
        ),
        migrations.CreateModel(
            name='QuesitonComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': "Question's comment",
                'db_table': 'question_comments',
            },
            bases=(models.Model, src.general.mixins.BaseToAllMixin),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=800, null=True)),
                ('slug', models.SlugField(blank=True, max_length=800, null=True)),
                ('checkings', models.JSONField(default=src.escritos.abstracts.default_dict)),
                ('total_votes', models.IntegerField(default=0)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('times_shared', models.PositiveIntegerField(default=0)),
                ('content', ckeditor.fields.RichTextField()),
                ('is_answered', models.BooleanField(default=False)),
                ('hide_question', models.BooleanField(default=False)),
                ('has_accepted_answer', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Question',
                'db_table': 'questions',
                'ordering': ['-created_at'],
            },
            bases=(models.Model, src.general.mixins.BaseToAllMixin, src.general.mixins.CommentsMixin, src.general.mixins.VotesMixin, src.general.mixins.CheckingsMixin),
        ),
    ]
