# Generated by Django 3.2.15 on 2022-11-12 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roboadvisor', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investor_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
