# Generated by Django 3.2.15 on 2022-09-07 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escritos', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='meta_information',
        ),
    ]
