# Generated by Django 3.2.15 on 2022-10-08 07:35

import apps.general.bases
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='extra_data',
            field=models.JSONField(default=apps.general.bases.default_dict),
        ),
    ]
