# Generated by Django 3.2.15 on 2022-10-16 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escritos', '0004_alter_term_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='term',
            old_name='extra_data',
            new_name='checkings',
        ),
    ]
