# Generated by Django 3.2.15 on 2022-10-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritos', '0005_rename_extra_data_term_checkings'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritestermshistorial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='favoritestermshistorial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='termscomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='termscomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
