CONTENT_FOR_PROMOTION = "promotion"
CONTENT_FOR_SUGGESTION = "suggestion"
CONTENT_FOR_ANNOUNCEMENT = "announcement"
CONTENT_FOR_WELCOME = "welcome"
CONTENT_FOR_ENGAGEMENT = "engagement"
CONTENT_FOR_NEWSLETTER = "newsletter"

WEB_OBJECTIVES = (
    CONTENT_FOR_PROMOTION,
    CONTENT_FOR_SUGGESTION,
    CONTENT_FOR_ANNOUNCEMENT,
    CONTENT_FOR_WELCOME,
    CONTENT_FOR_ENGAGEMENT,
    CONTENT_FOR_NEWSLETTER,
)

CORE_CAMPAIGN_FOCUS = (
    (CONTENT_FOR_PROMOTION, "Promotion"),
    (CONTENT_FOR_SUGGESTION, "Suggestion"),
    (CONTENT_FOR_ANNOUNCEMENT, "Announcement"),
    (CONTENT_FOR_WELCOME, "Welcome"),
    (CONTENT_FOR_ENGAGEMENT, "Engagement"),
    (CONTENT_FOR_NEWSLETTER, "Newsletter"),
)

CONTENT_FOR_ENGAGEMENT_USER_FIRST_CALL = f"{CONTENT_FOR_ENGAGEMENT}-user-first-call"
CONTENT_FOR_ENGAGEMENT_USER_NO_ACTIVE = f"{CONTENT_FOR_ENGAGEMENT}-user-no-active"
CONTENT_FOR_ENGAGEMENT_USER_LITTLE_ACTIVE = f"{CONTENT_FOR_ENGAGEMENT}-user-little-active"

CONTENT_FOR_NEWSLETTER_BLOG = f"{CONTENT_FOR_NEWSLETTER}-blog"
CONTENT_FOR_NEWSLETTER_PUBLIC_BLOG = f"{CONTENT_FOR_NEWSLETTER}-public-blog"
CONTENT_FOR_NEWSLETTER_TERM = f"{CONTENT_FOR_NEWSLETTER}-term"
CONTENT_FOR_NEWSLETTER_COMPANY = f"{CONTENT_FOR_NEWSLETTER}-company"
CONTENT_FOR_NEWSLETTER_COMPANY_NEWS = f"{CONTENT_FOR_NEWSLETTER_COMPANY}-news"
CONTENT_FOR_NEWSLETTER_COMPANY_REPORT = f"{CONTENT_FOR_NEWSLETTER_COMPANY}-report"

LIST_CONTENT_ENGAGEMENT = (
    CONTENT_FOR_ENGAGEMENT,
    CONTENT_FOR_ENGAGEMENT_USER_FIRST_CALL,
    CONTENT_FOR_ENGAGEMENT_USER_NO_ACTIVE,
    CONTENT_FOR_ENGAGEMENT_USER_LITTLE_ACTIVE,
)

LIST_CONTENT_NEWSLETTER = (
    CONTENT_FOR_NEWSLETTER,
    CONTENT_FOR_NEWSLETTER_BLOG,
    CONTENT_FOR_NEWSLETTER_PUBLIC_BLOG,
    CONTENT_FOR_NEWSLETTER_TERM,
    CONTENT_FOR_NEWSLETTER_COMPANY,
    CONTENT_FOR_NEWSLETTER_COMPANY_NEWS,
    CONTENT_FOR_NEWSLETTER_COMPANY_REPORT,
)

CONTENT_PURPOSES = (
    *CORE_CAMPAIGN_FOCUS,
    (CONTENT_FOR_ENGAGEMENT_USER_NO_ACTIVE, "Engagement user no active"),
    (CONTENT_FOR_ENGAGEMENT_USER_LITTLE_ACTIVE, "Engagement user little active"),
    (CONTENT_FOR_ENGAGEMENT_USER_FIRST_CALL, "Engagement user first call"),
    (CONTENT_FOR_NEWSLETTER_BLOG, "Newsletter for blog"),
    (CONTENT_FOR_NEWSLETTER_PUBLIC_BLOG, "Newsletter  for public blog"),
    (CONTENT_FOR_NEWSLETTER_TERM, "Newsletter for term"),
    (CONTENT_FOR_NEWSLETTER_COMPANY, "Newsletter for company"),
    (CONTENT_FOR_NEWSLETTER_COMPANY_NEWS, "Newsletter for company news"),
    (CONTENT_FOR_NEWSLETTER_COMPANY_REPORT, "Newsletter for company report"),
)

CONTENT_PURPOSES_MAP = {key: value for key, value in CONTENT_PURPOSES}

EMAIL_ALL = "all"
EMAIL_CAMPAIGN_RELATED = "campaign_related"
EMAIL_SELECTED = "selected"

WHOM_TO_SEND_EMAIL = (
    (EMAIL_ALL, "All"),
    (EMAIL_CAMPAIGN_RELATED, "Campaign related"),
    (EMAIL_SELECTED, "Selected"),
)

COMMENT_PURCHASED_PRODUCT = "Comenta tu úlitma compra"


ROADMAP_STATUS_FINISHED = "finished"
ROADMAP_STATUS_PENDING = "pending"
ROADMAP_STATUS_DOING = "doing"
ROADMAP_STATUS_TESTING = "testing"

ROADMAP_STATUS = (
    (ROADMAP_STATUS_FINISHED, "Finished"),
    (ROADMAP_STATUS_PENDING, "Pending"),
    (ROADMAP_STATUS_DOING, "Doing"),
    (ROADMAP_STATUS_TESTING, "Testing"),
)

ROADMAP_STATUS_MAP = {
    ROADMAP_STATUS_FINISHED: "Acabado",
    ROADMAP_STATUS_PENDING: "En espera",
    ROADMAP_STATUS_DOING: "En desarrollo",
    ROADMAP_STATUS_TESTING: "Testeando",
}

ROADMAP_STATUS_MAP_COLOR_ICON = {
    ROADMAP_STATUS_FINISHED: {"color": "success", "icon": "fas fa-check"},
    ROADMAP_STATUS_PENDING: {"color": "warning", "icon": "fas fa-clock"},
    ROADMAP_STATUS_DOING: {"color": "primary", "icon": "fa fa-vial"},
    ROADMAP_STATUS_TESTING: {"color": "danger", "icon": "fa fa-spinner"},
}
