# Generated by Django 3.2.15 on 2022-11-04 20:21

import apps.general.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('periods', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritesSuperinvestorsHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('added', models.BooleanField(default=False)),
                ('removed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Superinvestor favorita',
                'verbose_name_plural': 'Superinvestor favoritas',
                'db_table': 'favorites_superinvestor_historial',
            },
            bases=(models.Model, apps.general.mixins.BaseToAllMixin),
        ),
        migrations.CreateModel(
            name='Superinvestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=600, null=True)),
                ('fund_name', models.CharField(blank=True, max_length=600, null=True)),
                ('info_accronym', models.CharField(blank=True, max_length=20, null=True)),
                ('slug', models.CharField(blank=True, max_length=600, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('has_error', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=600, null=True)),
            ],
            options={
                'verbose_name': 'Superinvestor',
                'verbose_name_plural': 'Superinvestors',
                'db_table': 'superinvestors',
            },
        ),
        migrations.CreateModel(
            name='SuperinvestorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField(blank=True, null=True)),
                ('not_registered_company', models.BooleanField(default=False)),
                ('need_verify_company', models.BooleanField(default=False)),
                ('portfolio_change', models.FloatField(blank=True, null=True)),
                ('movement', models.CharField(blank=True, max_length=500, null=True)),
                ('shares', models.FloatField(blank=True, null=True)),
                ('reported_price', models.FloatField(blank=True, null=True)),
                ('portfolio_weight', models.FloatField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresas.company')),
                ('period_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='periods.period')),
                ('superinvestor_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='super_investors.superinvestor')),
            ],
            options={
                'verbose_name': 'Superinvestor history',
                'verbose_name_plural': 'Superinvestors history',
                'db_table': 'superinvestors_history',
                'ordering': ['period_related'],
                'get_latest_by': ['period_related'],
            },
        ),
        migrations.CreateModel(
            name='SuperinvestorActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField(blank=True, null=True)),
                ('not_registered_company', models.BooleanField(default=False)),
                ('need_verify_company', models.BooleanField(default=False)),
                ('portfolio_change', models.FloatField(blank=True, null=True)),
                ('percentage_share_change', models.FloatField(blank=True, null=True)),
                ('share_change', models.FloatField(blank=True, null=True)),
                ('is_new', models.BooleanField(default=False)),
                ('movement', models.PositiveIntegerField(blank=True, choices=[(1, 'Compra'), (2, 'Venta')], null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresas.company')),
                ('period_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='periods.period')),
                ('superinvestor_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='super_investors.superinvestor')),
            ],
            options={
                'verbose_name': 'Superinvestor activity',
                'verbose_name_plural': 'Superinvestors activity',
                'db_table': 'superinvestors_activity',
                'ordering': ['period_related'],
                'get_latest_by': ['period_related'],
            },
        ),
        migrations.CreateModel(
            name='FavoritesSuperinvestorsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superinvestor', models.ManyToManyField(blank=True, to='super_investors.Superinvestor')),
            ],
            options={
                'verbose_name': 'Lista de superinvestor favoritas',
                'verbose_name_plural': 'Lista de superinvestor favoritas',
                'db_table': 'favorites_superinvestor_list',
            },
        ),
    ]
